extends Node
## AUTO-GENERATED from horizonidle-godot content. Autoloaded as `GameData`.

const RESOURCES := {
	"Water": {"name": "Water", "color": "b0895a", "value": 0},
	"Dirt": {"name": "Dirt", "color": "b0895a", "value": 0},
	"Wood": {"name": "Wood", "color": "b0895a", "value": 0},
	"Spodumene": {"name": "Lithium Ore", "color": "b0895a", "value": 5},
	"Bauxite": {"name": "Bauxite Ore", "color": "b0895a", "value": 5},
	"ZincOre": {"name": "Zinc Ore", "color": "b0895a", "value": 5},
	"Cassiterite": {"name": "Cassiterite Ore", "color": "b0895a", "value": 5},
	"Quartz": {"name": "Quartz Crystal", "color": "b0895a", "value": 5},
	"Malachite": {"name": "Malachite Ore", "color": "b0895a", "value": 5},
	"H": {"name": "Hydrogen", "color": "6ad36a", "value": 2},
	"He": {"name": "Helium", "color": "7fd0e0", "value": 2},
	"Li": {"name": "Lithium", "color": "e0734f", "value": 20},
	"Be": {"name": "Beryllium", "color": "e0a24f", "value": 8},
	"B": {"name": "Boron", "color": "9ad36a", "value": 8},
	"C": {"name": "Carbon", "color": "6ad36a", "value": 5},
	"N": {"name": "Nitrogen", "color": "6ad36a", "value": 2},
	"O": {"name": "Oxygen", "color": "6ad36a", "value": 2},
	"Si": {"name": "Silicon", "color": "9ad36a", "value": 23},
	"Ge": {"name": "Germanium", "color": "9ad36a", "value": 30},
	"Fe": {"name": "Iron", "color": "c4c8d0", "value": 5},
	"Semiconductor": {"name": "Semiconductor", "color": "5ad1e0", "value": 115},
	"AdvCircuit": {"name": "Advanced Circuit", "color": "5ad1e0", "value": 150},
	"Chip": {"name": "Microchip", "color": "5ad1e0", "value": 50},
	"Steel": {"name": "Steel", "color": "cfd3da", "value": 55},
	"Superalloy": {"name": "Superalloy", "color": "cfd3da", "value": 60},
	"Graphite": {"name": "Graphite", "color": "9aa3af", "value": 40},
	"Scrap": {"name": "Recycled Scrap", "color": "b0895a", "value": 2},
	"Cu": {"name": "Copper", "color": "c4c8d0", "value": 22},
	"Au": {"name": "Gold", "color": "c4c8d0", "value": 50},
	"Ti": {"name": "Titanium", "color": "c4c8d0", "value": 45},
	"W": {"name": "Tungsten", "color": "c4c8d0", "value": 30},
	"NavData": {"name": "Navigation Data", "color": "9aa3af", "value": 50},
	"Hydraulics": {"name": "Hydraulic System", "color": "5ad1e0", "value": 190},
	"Circuit": {"name": "Circuit Board", "color": "5ad1e0", "value": 80},
	"Mesh": {"name": "Nanoweave Mesh", "color": "e0b44f", "value": 40},
	"Seal": {"name": "Hull Sealant", "color": "e0b44f", "value": 40},
	"Fiber": {"name": "Carbon Fiber", "color": "5ad1e0", "value": 25},
	"Resin": {"name": "Polymer Resin", "color": "5ad1e0", "value": 20},
	"CoolantCell": {"name": "Helium Coolant Cell", "color": "5ad1e0", "value": 50},
	"SlugT1": {"name": "Ferrite Rounds", "color": "9aa3af", "value": 2},
	"SlugT2": {"name": "Tungsten Sabot", "color": "9aa3af", "value": 17},
	"SlugT1S": {"name": "Steel Slugs", "color": "9aa3af", "value": 17},
	"CellT1": {"name": "Focus Crystal", "color": "9aa3af", "value": 2},
	"CellT2": {"name": "Plasma Cell", "color": "9aa3af", "value": 17},
	"U": {"name": "Uranium", "color": "b07ad6", "value": 50},
	"SlugT3": {"name": "Depleted Uranium Round", "color": "9aa3af", "value": 60},
	"CellT3": {"name": "Vaporizer Cell", "color": "9aa3af", "value": 60},
	"LaserSight": {"name": "LaserSight", "color": "9aa3af", "value": 100},
	"kinetic_shell": {"name": "Kinetic Shells", "color": "9aa3af", "value": 15},
	"energy_cell": {"name": "Energy Cells", "color": "9aa3af", "value": 15},
	"missile": {"name": "HE Missiles", "color": "9aa3af", "value": 40},
	"VoidArtifact": {"name": "Void Artifact", "color": "b07ad6", "value": 500},
	"QuantumCore": {"name": "Quantum Core", "color": "b07ad6", "value": 2000},
	"AncientComponent": {"name": "Ancient Component", "color": "b07ad6", "value": 1000},
	"BatteryT1": {"name": "Basic Battery", "color": "5ad1e0", "value": 60},
	"BatteryT2": {"name": "Improved Battery", "color": "5ad1e0", "value": 150},
	"BatteryT3": {"name": "Zero-Point Module", "color": "5ad1e0", "value": 500},
	"Res1": {"name": "Common Research Artifact", "color": "9aa3af", "value": 25},
	"DroneCore": {"name": "Drone Core", "color": "9aa3af", "value": 15},
	"SalvageData": {"name": "Salvage Data", "color": "9aa3af", "value": 30},
	"PirateManifest": {"name": "Pirate Manifest", "color": "9aa3af", "value": 50},
	"Res2": {"name": "Rare Research Artifact", "color": "9aa3af", "value": 75},
	"Res3": {"name": "Exotic Research Artifact", "color": "9aa3af", "value": 200},
	"Trophy_Lunar": {"name": "Lunar Command Trophy", "color": "9aa3af", "value": 5000},
	"Trophy_Belt": {"name": "Belt Warden Trophy", "color": "9aa3af", "value": 15000},
	"Trophy_Mars": {"name": "Martian Sovereign Trophy", "color": "9aa3af", "value": 35000},
	"Trophy_Titan": {"name": "Titan Overlord Trophy", "color": "9aa3af", "value": 75000},
	"Trophy_Alpha": {"name": "Alpha Vanguard Trophy", "color": "9aa3af", "value": 150000},
	"Trophy_Beta": {"name": "Beta Governor Trophy", "color": "9aa3af", "value": 300000},
	"Trophy_Gamma": {"name": "Gamma Ravager Trophy", "color": "9aa3af", "value": 600000},
	"Trophy_Delta": {"name": "Delta Sentinel Trophy", "color": "9aa3af", "value": 1200000},
	"Trophy_Zeta": {"name": "Zeta Purifier Trophy", "color": "9aa3af", "value": 2500000},
	"Trophy_Epsilon": {"name": "Void Conqueror Trophy", "color": "9aa3af", "value": 10000000},
	"ColonySalvage": {"name": "Colony Salvage", "color": "b0895a", "value": 150},
	"RadIsotope": {"name": "Radioactive Isotope", "color": "b0895a", "value": 300},
	"NitroCoolant": {"name": "Cryo-Shield Matrix", "color": "5ad1e0", "value": 35},
	"nanite_swarm": {"name": "Nanite Repair Swarm", "color": "e0b44f", "value": 500},
	"MiteChitin": {"name": "Mite Chitin", "color": "b0895a", "value": 5},
	"ChitinPatch": {"name": "Chitin Hull Patch", "color": "e0b44f", "value": 10},
	"EmergencyPatch": {"name": "Emergency Patch", "color": "e0b44f", "value": 40},
	"BasicBooster": {"name": "Shield Booster", "color": "e0b44f", "value": 40},
	"Al": {"name": "Aluminum", "color": "9aa3af", "value": 15},
	"Mn": {"name": "Manganese", "color": "c4c8d0", "value": 25},
	"Cr": {"name": "Chromium", "color": "c4c8d0", "value": 42},
	"Ni": {"name": "Nickel", "color": "c4c8d0", "value": 40},
	"Sn": {"name": "Tin", "color": "9aa3af", "value": 15},
	"Bronze": {"name": "Bronze", "color": "cfd3da", "value": 60},
	"Pentlandite": {"name": "Pentlandite Ore", "color": "b0895a", "value": 15},
	"Chromite": {"name": "Chromite Ore", "color": "b0895a", "value": 15},
	"Dolomite": {"name": "Dolomite", "color": "b0895a", "value": 5},
	"Germanit": {"name": "Germanite Ore", "color": "b0895a", "value": 15},
	"PtOre": {"name": "Platinum Ore", "color": "b0895a", "value": 25},
	"Mg": {"name": "Magnesium", "color": "e0a24f", "value": 40},
	"Co": {"name": "Cobalt", "color": "c4c8d0", "value": 45},
	"Ag": {"name": "Silver", "color": "c4c8d0", "value": 60},
	"Pt": {"name": "Platinum", "color": "c4c8d0", "value": 150},
	"Pd": {"name": "Palladium", "color": "c4c8d0", "value": 120},
	"Ir": {"name": "Iridium", "color": "c4c8d0", "value": 300},
	"Os": {"name": "Osmium", "color": "c4c8d0", "value": 350},
	"AlMgAlloy": {"name": "Al-Mg Alloy", "color": "cfd3da", "value": 65},
	"IrWAlloy": {"name": "Iridium-Tungsten Alloy", "color": "cfd3da", "value": 250},
	"Neutronium": {"name": "Neutronium", "color": "e05fb0", "value": 2500},
	"ExoticIsotope": {"name": "Exotic Isotope", "color": "e05fb0", "value": 800},
	"AntimatterParticle": {"name": "Antimatter Particle", "color": "e05fb0", "value": 1500},
	"AntimatterFuel": {"name": "Antimatter Fuel Cell", "color": "9aa3af", "value": 5000},
	"VoidEssence": {"name": "Void Essence", "color": "e05fb0", "value": 2000},
	"PrimordialShard": {"name": "Primordial Shard", "color": "e05fb0", "value": 10000},
	"OmegaPlating": {"name": "Omega Plating", "color": "5ad1e0", "value": 1500},
	"ChronoCore": {"name": "Chrono Core", "color": "e05fb0", "value": 3000},
	"AncientTech": {"name": "Ancient Technology", "color": "b07ad6", "value": 1200},
	"TargetingChip": {"name": "Targeting Chip", "color": "5ad1e0", "value": 150},
	"BiohazardSample": {"name": "Biohazard Sample", "color": "b0895a", "value": 100},
	"PathogenCore": {"name": "Pathogen Core", "color": "e05fb0", "value": 500},
	"MutatedTissue": {"name": "Mutated Tissue", "color": "b0895a", "value": 150},
	"BioWeaponCoating": {"name": "Bio-Weapon Coating", "color": "5ad1e0", "value": 400},
	"AIProcessor": {"name": "AI Processor", "color": "5ad1e0", "value": 1000},
	"RegenPlating": {"name": "Regenerative Plating", "color": "5ad1e0", "value": 800},
	"StolenCargo": {"name": "Stolen Cargo", "color": "9aa3af", "value": 100},
	"SwarmFragment": {"name": "Swarm Fragment", "color": "b0895a", "value": 20},
	"CryoCell": {"name": "Cryo Cell", "color": "5ad1e0", "value": 60},
	"TurretCore": {"name": "Turret Core", "color": "5ad1e0", "value": 200},
	"CoBattery": {"name": "Cobalt Battery", "color": "5ad1e0", "value": 250},
	"MgBattery": {"name": "Magnesium Battery", "color": "5ad1e0", "value": 180},
	"PdFuelCell": {"name": "Palladium Fuel Cell", "color": "5ad1e0", "value": 1200},
	"AgCatalyst": {"name": "Silver Catalyst", "color": "5ad1e0", "value": 400},
	"PtCatalyst": {"name": "Platinum Catalyst", "color": "5ad1e0", "value": 2000},
	"SuperconductingMagnet": {"name": "Superconducting Magnet", "color": "5ad1e0", "value": 800},
	"AICore": {"name": "AI Core", "color": "5ad1e0", "value": 1500},
	"ReactiveCore": {"name": "Reactive Core", "color": "5ad1e0", "value": 600},
	"IrPlate": {"name": "Iridium Plate", "color": "5ad1e0", "value": 400},
	"OsCore": {"name": "Osmium Core", "color": "5ad1e0", "value": 2500},
	"ColonyDataCore": {"name": "Colony Data Core", "color": "9aa3af", "value": 500},
	"VoidCrystal": {"name": "Void Crystal", "color": "b0895a", "value": 200},
	"Diamond": {"name": "Diamond", "color": "b0895a", "value": 100},
	"SyntheticCrystal": {"name": "Synthetic Crystal", "color": "b0895a", "value": 80},
	"AlWire": {"name": "Aluminum Wire", "color": "5ad1e0", "value": 20},
	"AIMatrix": {"name": "AI Matrix", "color": "5ad1e0", "value": 100},
	"AdvMaintenanceKit": {"name": "Adv. Maintenance Kit", "color": "5ad1e0", "value": 100},
	"CapacitorShard": {"name": "Capacitor Shard", "color": "5ad1e0", "value": 100},
	"CellT4": {"name": "Heavy Plasma Cell", "color": "5ad1e0", "value": 100},
	"CompositeWeave": {"name": "Composite Weave", "color": "5ad1e0", "value": 100},
	"ExoticMatter": {"name": "Exotic Matter", "color": "5ad1e0", "value": 100},
	"FertileSoil": {"name": "Fertile Soil", "color": "5ad1e0", "value": 100},
	"Food": {"name": "Hydroponic Food", "color": "5ad1e0", "value": 100},
	"GalvanizedSteel": {"name": "Galvanized Steel", "color": "5ad1e0", "value": 100},
	"Germanium": {"name": "Germanium", "color": "5ad1e0", "value": 100},
	"Gold": {"name": "Gold", "color": "5ad1e0", "value": 100},
	"HE_Missile": {"name": "High-Explosive Missile", "color": "5ad1e0", "value": 100},
	"IonField": {"name": "Ion Field Projector", "color": "5ad1e0", "value": 100},
	"NuclearFuel": {"name": "Nuclear Fuel", "color": "5ad1e0", "value": 100},
	"OmegaAccelerator": {"name": "Omega Accelerator", "color": "5ad1e0", "value": 100},
	"Photon_Torpedo": {"name": "Photon Torpedo", "color": "5ad1e0", "value": 100},
	"PrimordialArmor": {"name": "Primordial Armor", "color": "5ad1e0", "value": 100},
	"PurifiedCompound": {"name": "Purified Compound", "color": "5ad1e0", "value": 100},
	"QuarantineClearance": {"name": "Quarantine Clearance", "color": "5ad1e0", "value": 100},
	"Seeker_Missile": {"name": "Seeker Missile", "color": "5ad1e0", "value": 100},
	"SlugT4": {"name": "Hyper-Velocity Slug", "color": "5ad1e0", "value": 100},
	"StainlessSteel": {"name": "Stainless Steel", "color": "5ad1e0", "value": 100},
	"TemporalModule": {"name": "Temporal Stabilizer", "color": "5ad1e0", "value": 100},
	"VoidBattery": {"name": "Void Battery", "color": "5ad1e0", "value": 100},
	"ZeroPoint": {"name": "Zero-Point Injector", "color": "5ad1e0", "value": 100},
	"Zn": {"name": "Zinc", "color": "5ad1e0", "value": 100},
	"CrackedCrimsonCore": {"name": "Cracked Crimson Core", "color": "b07ad6", "value": 5000},
	"StableCrimsonCore": {"name": "Stable Crimson Core", "color": "b07ad6", "value": 15000},
	"PristineCrimsonCore": {"name": "Pristine Crimson Core", "color": "b07ad6", "value": 50000},
	"CrackedCobaltCore": {"name": "Cracked Cobalt Core", "color": "b07ad6", "value": 5000},
	"StableCobaltCore": {"name": "Stable Cobalt Core", "color": "b07ad6", "value": 15000},
	"PristineCobaltCore": {"name": "Pristine Cobalt Core", "color": "b07ad6", "value": 50000},
	"CrackedTopazCore": {"name": "Cracked Topaz Core", "color": "b07ad6", "value": 5000},
	"StableTopazCore": {"name": "Stable Topaz Core", "color": "b07ad6", "value": 15000},
	"PristineTopazCore": {"name": "Pristine Topaz Core", "color": "b07ad6", "value": 50000},
	"CrackedAmethystCore": {"name": "Cracked Amethyst Core", "color": "b07ad6", "value": 5000},
	"StableAmethystCore": {"name": "Stable Amethyst Core", "color": "b07ad6", "value": 15000},
	"PristineAmethystCore": {"name": "Pristine Amethyst Core", "color": "b07ad6", "value": 50000},
	"credits": {"name": "credits", "color": "9aa3af", "value": 1},
	"TitanClearance": {"name": "Titan Clearance", "color": "9aa3af", "value": 1},
	"Platinum": {"name": "Platinum", "color": "9aa3af", "value": 1},
	"Osmium": {"name": "Osmium", "color": "9aa3af", "value": 1},
}

const GATHER_CATS := [
	{"id": "terrestrial", "label": "Terrestrial"},
	{"id": "orbital", "label": "Orbital"},
	{"id": "void", "label": "Void"},
]
const GATHER := {
	"gather_dirt": {"name": "Excavate Soil", "loot": [["Dirt", 1.0, 8, 10]], "xp": 8, "level_req": 1, "duration": 3.0, "category": "terrestrial"},
	"extract_manganese": {"name": "Extract Manganese", "loot": [["Mn", 1.0, 1, 2], ["Fe", 0.5, 1, 2]], "xp": 18, "level_req": 15, "duration": 4.0, "category": "terrestrial", "research_req": "adv_materials"},
	"collect_water": {"name": "Pump Water", "loot": [["Water", 1.0, 8, 10]], "xp": 12, "level_req": 3, "duration": 4.0, "category": "terrestrial", "research_req": "fluid_dynamics"},
	"mine_cassiterite": {"name": "Mine Cassiterite", "loot": [["Cassiterite", 1.0, 1, 2]], "xp": 20, "level_req": 8, "duration": 4.0, "category": "terrestrial", "research_req": "basic_engineering"},
	"gather_wood": {"name": "Deforest Zone", "loot": [["Wood", 1.0, 8, 10]], "xp": 10, "level_req": 5, "duration": 4.0, "category": "terrestrial"},
	"mine_dolomite": {"name": "Quarry Dolomite", "loot": [["Dolomite", 1.0, 1, 3], ["Dirt", 0.5, 1, 2]], "xp": 18, "level_req": 15, "duration": 4.0, "category": "terrestrial", "research_req": "adv_materials"},
	"mine_bauxite": {"name": "Strip Mine Bauxite", "loot": [["Bauxite", 1.0, 1, 2]], "xp": 11, "level_req": 12, "duration": 4.0, "category": "terrestrial", "research_req": "lightweight_alloys"},
	"extract_pentlandite": {"name": "Extract Pentlandite", "loot": [["Pentlandite", 1.0, 1, 2], ["Fe", 0.5, 1, 2]], "xp": 25, "level_req": 25, "duration": 4.0, "category": "terrestrial", "research_req": "adv_materials"},
	"extract_chromite": {"name": "Extract Chromite", "loot": [["Chromite", 1.0, 1, 2], ["Fe", 0.5, 1, 2]], "xp": 30, "level_req": 30, "duration": 4.0, "category": "terrestrial", "research_req": "adv_materials"},
	"extract_salts": {"name": "Extract Lithium Salt", "loot": [["Spodumene", 1.0, 1, 3]], "xp": 10, "level_req": 4, "duration": 4.0, "category": "terrestrial", "research_req": "basic_engineering"},
	"mine_zinc_ore": {"name": "Extract Zinc Ore", "loot": [["ZincOre", 1.0, 1, 3], ["Si", 0.4, 1, 1]], "xp": 25, "level_req": 25, "duration": 4.0, "category": "terrestrial", "research_req": "smelting"},
	"mine_malachite": {"name": "Extract Malachite", "loot": [["Malachite", 1.0, 1, 2]], "xp": 14, "level_req": 10, "duration": 4.0, "category": "terrestrial", "research_req": "basic_engineering"},
	"mine_quartz": {"name": "Collect Quartz Clusters", "loot": [["Quartz", 1.0, 1, 3]], "xp": 22, "level_req": 22, "duration": 4.0, "category": "terrestrial", "research_req": "adv_materials"},
	"harvest_nebula": {"name": "Harvest Nebula", "loot": [["H", 1.0, 1, 2], ["He", 1.0, 1, 1]], "xp": 15, "level_req": 40, "duration": 4.0, "category": "orbital", "research_req": "energy_metrics"},
	"mine_germanit": {"name": "Excavate Germanite Deposits", "loot": [["Germanit", 1.0, 1, 2]], "xp": 35, "level_req": 35, "duration": 4.0, "category": "terrestrial"},
	"extract_platinum": {"name": "Extract Platinum samples", "loot": [["PtOre", 1.0, 1, 3], ["Ti", 0.2, 1, 2]], "xp": 80, "level_req": 45, "duration": 4.0, "category": "orbital", "research_req": "precious_metal_refining"},
	"mine_iridium": {"name": "Mine Iridium Crystals", "loot": [["Ir", 1.0, 1, 2], ["PtOre", 0.3, 1, 1]], "xp": 150, "level_req": 60, "duration": 4.0, "category": "void", "research_req": "iridium_metallurgy"},
	"harvest_osmium": {"name": "Condense Osmium Vapor", "loot": [["Os", 1.0, 1, 1], ["Ir", 0.2, 1, 1]], "xp": 300, "level_req": 75, "duration": 4.0, "category": "void", "research_req": "exotic_metallurgy"},
	"harvest_void_essence": {"name": "Harvest Void Essence", "loot": [["VoidEssence", 1.0, 1, 2]], "xp": 500, "level_req": 85, "duration": 4.0, "category": "void", "research_req": "void_navigation"},
	"extract_chrono_crystals": {"name": "Extract Chrono Crystals", "loot": [["ChronoCore", 1.0, 1, 1], ["VoidEssence", 0.3, 1, 1]], "xp": 800, "level_req": 92, "duration": 4.0, "category": "void", "research_req": "void_navigation"},
}

const CRAFT_CATS := [
	{"id": "basics", "label": "Basics"},
	{"id": "processing", "label": "Processing"},
	{"id": "refining", "label": "Refining"},
	{"id": "salvage", "label": "Salvage"},
	{"id": "consumables_hull", "label": "Hull Repair"},
	{"id": "consumables_shield", "label": "Shielding"},
	{"id": "endgame", "label": "Endgame"},
	{"id": "misc", "label": "Other"},
]
const CRAFT := {
	"sift_dirt_dry": {"name": "Dry Sifting", "inputs": {"Dirt": 10}, "outputs": {"Fe": 3}, "bonus": [["Si", 0.2, 1, 1]], "xp": 3, "level_req": 1, "duration": 5.0, "category": "basics", "research_req": "basic_engineering"},
	"charcoal_burning": {"name": "Charcoal Kiln", "inputs": {"Wood": 5}, "outputs": {"C": 10}, "bonus": [], "xp": 5, "level_req": 3, "duration": 4.0, "category": "basics"},
	"electrolysis": {"name": "Water Electrolysis", "inputs": {"Water": 5}, "outputs": {"H": 20, "O": 10}, "bonus": [], "xp": 5, "level_req": 2, "duration": 2.0, "category": "basics", "research_req": "fluid_dynamics"},
	"centrifuge_dirt": {"name": "Mineral Washing", "inputs": {"Dirt": 5, "Water": 5}, "outputs": {"Fe": 5, "Si": 3}, "bonus": [], "xp": 5, "level_req": 1, "duration": 3.0, "category": "basics", "research_req": "basic_engineering"},
	"smelt_steel_basic": {"name": "Basic Steel Smelting", "inputs": {"Fe": 5, "C": 2}, "outputs": {"Steel": 5}, "bonus": [], "xp": 20, "level_req": 12, "duration": 5.0, "category": "misc", "research_req": "smelting"},
	"smelt_copper": {"name": "Copper Smelting", "inputs": {"Malachite": 2, "C": 1}, "outputs": {"Cu": 1}, "bonus": [], "xp": 15, "level_req": 15, "duration": 5.0, "category": "misc", "research_req": "basic_engineering"},
	"smelt_zinc": {"name": "Zinc Reduction", "inputs": {"ZincOre": 3, "C": 1}, "outputs": {"Zn": 2}, "bonus": [], "xp": 12, "level_req": 18, "duration": 4.0, "category": "misc"},
	"refine_cassiterite": {"name": "Tin Smelting", "inputs": {"Cassiterite": 3, "C": 1}, "outputs": {"Sn": 2}, "bonus": [], "xp": 25, "level_req": 20, "duration": 6.0, "category": "misc", "research_req": "smelting"},
	"refine_pentlandite": {"name": "Nickel Extraction", "inputs": {"Pentlandite": 3, "C": 1}, "outputs": {"Ni": 2}, "bonus": [], "xp": 30, "level_req": 22, "duration": 6.0, "category": "misc", "research_req": "smelting"},
	"refine_chromite": {"name": "Chromium Reduction", "inputs": {"Chromite": 3, "Al": 1}, "outputs": {"Cr": 2}, "bonus": [], "xp": 35, "level_req": 25, "duration": 8.0, "category": "misc", "research_req": "metallurgy_advanced"},
	"smelt_quartz": {"name": "Silicon Smelting", "inputs": {"Quartz": 2, "C": 1}, "outputs": {"Si": 1}, "bonus": [], "xp": 20, "level_req": 20, "duration": 6.0, "category": "misc"},
	"smelt_steel_oxygen": {"name": "Oxygen-Enriched Smelting", "inputs": {"Fe": 10, "C": 4, "O": 4}, "outputs": {"Steel": 10}, "bonus": [], "xp": 25, "level_req": 40, "duration": 5.0, "category": "misc", "research_req": "smelting"},
	"press_graphite": {"name": "Graphite Press", "inputs": {"C": 5}, "outputs": {"Graphite": 1}, "bonus": [], "xp": 20, "level_req": 25, "duration": 6.0, "category": "misc", "research_req": "adv_materials"},
	"analyze_artifact": {"name": "Analyze Void Artifact", "inputs": {"VoidArtifact": 1}, "outputs": {}, "bonus": [["Cu", 1.0, 10, 20], ["Chip", 0.3, 1, 2], ["NavData", 0.2, 1, 2], ["AncientComponent", 0.05, 1, 1]], "xp": 200, "level_req": 50, "duration": 10.0, "category": "misc", "research_req": "xeno_archaeology"},
	"decrypt_nav_data": {"name": "Decrypt Nav-Data", "inputs": {"SalvageData": 5}, "outputs": {"NavData": 1}, "bonus": [], "xp": 50, "level_req": 20, "duration": 30.0, "category": "misc", "research_req": "basic_engineering"},
	"upgrade_rare_artifact": {"name": "Synthesize Rare Artifact", "inputs": {"Res1": 100, "Circuit": 10}, "outputs": {"Res2": 1}, "bonus": [], "xp": 100, "level_req": 35, "duration": 8.0, "category": "misc", "research_req": "smelting"},
	"upgrade_exotic_artifact": {"name": "Compile Exotic Artifact", "inputs": {"Res2": 5, "AdvCircuit": 2, "NavData": 5}, "outputs": {"Res3": 1}, "bonus": [], "xp": 300, "level_req": 60, "duration": 60.0, "category": "misc", "research_req": "sector_alpha_decryption"},
	"craft_carbon_fiber": {"name": "Carbon Fiber", "inputs": {"C": 3}, "outputs": {"Fiber": 1}, "bonus": [], "xp": 10, "level_req": 8, "duration": 5.0, "category": "misc", "research_req": "combustion"},
	"craft_polymer": {"name": "Polymer Resin", "inputs": {"C": 1, "H": 2, "O": 1}, "outputs": {"Resin": 1}, "bonus": [], "xp": 10, "level_req": 10, "duration": 5.0, "category": "misc"},
	"craft_aluminum_alloy": {"name": "Aluminum-Magnesium Alloy", "inputs": {"Al": 3, "Mg": 1}, "outputs": {"AlMgAlloy": 2}, "bonus": [], "xp": 30, "level_req": 24, "duration": 5.0, "category": "misc", "research_req": "lightweight_alloys"},
	"galvanize_steel": {"name": "Galvanized Steel", "inputs": {"Steel": 2, "Zn": 1}, "outputs": {"GalvanizedSteel": 2}, "bonus": [], "xp": 40, "level_req": 25, "duration": 4.0, "category": "misc", "research_req": "smelting"},
	"craft_stainless_steel": {"name": "Stainless Steel Alloy", "inputs": {"Fe": 5, "Cr": 2, "Ni": 1}, "outputs": {"StainlessSteel": 4}, "bonus": [], "xp": 60, "level_req": 30, "duration": 8.0, "category": "misc", "research_req": "metallurgy_advanced"},
	"craft_emergency_patch": {"name": "Emergency Hull Patch", "inputs": {"Fe": 20}, "outputs": {"EmergencyPatch": 1}, "bonus": [], "xp": 10, "level_req": 1, "duration": 10.0, "category": "consumables_hull"},
	"craft_adv_maintenance_kit": {"name": "Adv. Maintenance Kit", "inputs": {"AlWire": 3, "Circuit": 5, "Superalloy": 1, "Steel": 50, "Ti": 15}, "outputs": {"AdvMaintenanceKit": 1}, "bonus": [], "xp": 40, "level_req": 40, "duration": 15.0, "category": "consumables_hull", "research_req": "basic_electronics"},
	"craft_capacitor_shard": {"name": "Capacitor Shard", "inputs": {"Si": 5, "Al": 2}, "outputs": {"CapacitorShard": 1}, "bonus": [], "xp": 5, "level_req": 2, "duration": 5.0, "category": "consumables_shield"},
	"craft_basic_booster": {"name": "Basic Shield Booster", "inputs": {"Si": 20, "BatteryT1": 1}, "outputs": {"BasicBooster": 1}, "bonus": [], "xp": 10, "level_req": 8, "duration": 10.0, "category": "consumables_shield"},
	"craft_ion_field": {"name": "Ion Field Projector", "inputs": {"AlWire": 5, "MgBattery": 1}, "outputs": {"IonField": 1}, "bonus": [], "xp": 25, "level_req": 18, "duration": 15.0, "category": "consumables_shield", "research_req": "basic_electronics"},
	"craft_nanoweave": {"name": "Nanoweave Mesh", "inputs": {"Fiber": 5, "Si": 10}, "outputs": {"Mesh": 1}, "bonus": [], "xp": 25, "level_req": 15, "duration": 15.0, "category": "consumables_hull"},
	"craft_sealant": {"name": "Hull Sealant", "inputs": {"Resin": 10, "Steel": 8}, "outputs": {"Seal": 1}, "bonus": [], "xp": 30, "level_req": 25, "duration": 15.0, "category": "consumables_hull", "research_req": "metallurgy_advanced"},
	"craft_chitin_patch": {"name": "Biosynthetic Hull Patch", "inputs": {"MiteChitin": 10, "Steel": 5}, "outputs": {"ChitinPatch": 1}, "bonus": [], "xp": 8, "level_req": 5, "duration": 8.0, "category": "consumables_hull", "research_req": "basic_engineering"},
	"craft_slug_t1": {"name": "Ferrite Rounds", "inputs": {"Fe": 1}, "outputs": {"SlugT1": 20}, "bonus": [], "xp": 5, "level_req": 1, "duration": 5.0, "category": "misc"},
	"craft_cell_t1": {"name": "Focus Crystal", "inputs": {"Si": 1}, "outputs": {"CellT1": 20}, "bonus": [], "xp": 7, "level_req": 2, "duration": 5.0, "category": "misc"},
	"craft_slug_t2": {"name": "Tungsten Sabot", "inputs": {"Steel": 1, "W": 1}, "outputs": {"SlugT2": 20}, "bonus": [], "xp": 40, "level_req": 32, "duration": 10.0, "category": "misc", "research_req": "processing_tungsten"},
	"craft_slug_t1s": {"name": "Steel Slugs", "inputs": {"Steel": 1}, "outputs": {"SlugT1S": 20}, "bonus": [], "xp": 20, "level_req": 24, "duration": 10.0, "category": "misc"},
	"craft_cell_t2": {"name": "Plasma Cell", "inputs": {"H": 5, "Resin": 1}, "outputs": {"CellT2": 20}, "bonus": [], "xp": 40, "level_req": 34, "duration": 10.0, "category": "misc"},
	"craft_coolant_cell": {"name": "Helium Coolant Cell", "inputs": {"He": 10, "NitroCoolant": 5, "Steel": 2, "Li": 2}, "outputs": {"CoolantCell": 1}, "bonus": [], "xp": 80, "level_req": 42, "duration": 15.0, "category": "misc", "research_req": "cryogenic_systems"},
	"cryogenic_distillation": {"name": "Cryogenic Distillation", "inputs": {"H": 10, "O": 10}, "outputs": {"N": 5}, "bonus": [], "xp": 30, "level_req": 25, "duration": 20.0, "category": "misc", "research_req": "fluid_dynamics"},
	"nitrogen_coolant": {"name": "Cryo-Shield Matrix", "inputs": {"Circuit": 5, "AlMgAlloy": 10, "N": 250, "Li": 5}, "outputs": {"NitroCoolant": 1}, "bonus": [], "xp": 60, "level_req": 32, "duration": 15.0, "category": "consumables_shield", "research_req": "fluid_dynamics"},
	"craft_zero_point": {"name": "Zero-Point Injector", "inputs": {"BatteryT3": 1, "Superalloy": 2}, "outputs": {"ZeroPoint": 1}, "bonus": [], "xp": 60, "level_req": 42, "duration": 20.0, "category": "consumables_shield", "research_req": "energy_metrics"},
	"craft_slug_t3": {"name": "Depleted Uranium Round", "inputs": {"SlugT2": 20, "U": 1}, "outputs": {"SlugT3": 20}, "bonus": [], "xp": 120, "level_req": 55, "duration": 15.0, "category": "misc", "research_req": "ballistics_optimization"},
	"craft_slug_t4": {"name": "Hyper-Velocity Slug", "inputs": {"W": 10, "U": 3, "Superalloy": 1}, "outputs": {"SlugT4": 50}, "bonus": [], "xp": 180, "level_req": 65, "duration": 20.0, "category": "misc", "research_req": "ballistics_optimization"},
	"craft_cell_t3": {"name": "Vaporizer Cell", "inputs": {"CellT2": 20, "U": 1}, "outputs": {"CellT3": 20}, "bonus": [], "xp": 120, "level_req": 58, "duration": 15.0, "category": "misc", "research_req": "energy_metrics"},
	"craft_cell_t4": {"name": "Heavy Plasma Cell", "inputs": {"He": 10, "U": 3, "Superalloy": 1}, "outputs": {"CellT4": 20}, "bonus": [], "xp": 180, "level_req": 65, "duration": 20.0, "category": "misc", "research_req": "energy_metrics"},
	"craft_he_missile": {"name": "HE Missile", "inputs": {"Fe": 5, "C": 2}, "outputs": {"HE_Missile": 20}, "bonus": [], "xp": 20, "level_req": 5, "duration": 12.0, "category": "misc", "research_req": "combustion"},
	"craft_seeker_missile": {"name": "Seeker Missile", "inputs": {"Steel": 2, "Circuit": 1, "TargetingChip": 1}, "outputs": {"Seeker_Missile": 20}, "bonus": [], "xp": 50, "level_req": 25, "duration": 20.0, "category": "misc", "research_req": "advanced_rocketry"},
	"craft_photon_torpedo": {"name": "Photon Torpedo", "inputs": {"Superalloy": 2, "ExoticMatter": 1}, "outputs": {"Photon_Torpedo": 20}, "bonus": [], "xp": 200, "level_req": 60, "duration": 45.0, "category": "misc", "research_req": "capital_ship_armament"},
	"craft_circuit": {"name": "Basic Circuitry", "inputs": {"Si": 4, "DroneCore": 2}, "outputs": {"Circuit": 2}, "bonus": [], "xp": 50, "level_req": 6, "duration": 6.0, "category": "misc"},
	"craft_aluminum_wire": {"name": "Aluminum Wiring", "inputs": {"Al": 2, "Resin": 1}, "outputs": {"AlWire": 2}, "bonus": [], "xp": 35, "level_req": 30, "duration": 5.0, "category": "misc", "research_req": "basic_electronics"},
	"assemble_circuit_standard": {"name": "Standard Circuit Assembly", "inputs": {"Cu": 2, "Si": 3, "Resin": 1}, "outputs": {"Circuit": 3}, "bonus": [], "xp": 40, "level_req": 12, "duration": 6.0, "category": "misc", "research_req": "basic_electronics"},
	"craft_hydraulics": {"name": "Hydraulic Servo", "inputs": {"Steel": 2, "Resin": 1}, "outputs": {"Hydraulics": 1}, "bonus": [], "xp": 40, "level_req": 10, "duration": 10.0, "category": "misc", "research_req": "industrial_logistics"},
	"refine_lithium": {"name": "Refine Lithium", "inputs": {"Spodumene": 2}, "outputs": {"Li": 1}, "bonus": [], "xp": 7, "level_req": 3, "duration": 5.0, "category": "misc", "research_req": "basic_engineering"},
	"extract_germanium": {"name": "Germanite Smelting", "inputs": {"Germanit": 5}, "outputs": {"Germanium": 1}, "bonus": [], "xp": 40, "level_req": 36, "duration": 8.0, "category": "misc", "research_req": "combustion"},
	"craft_semiconductor": {"name": "Semiconductor Wafer", "inputs": {"Si": 2, "Germanium": 1}, "outputs": {"Semiconductor": 1}, "bonus": [], "xp": 50, "level_req": 38, "duration": 10.0, "category": "misc", "research_req": "adv_materials"},
	"refine_gold": {"name": "Gold Panning", "inputs": {"Dirt": 100, "Water": 100}, "outputs": {"Au": 1}, "bonus": [], "xp": 30, "level_req": 20, "duration": 12.0, "category": "misc", "research_req": "basic_engineering"},
	"gold_leaching": {"name": "Chemical Leaching", "inputs": {"Dirt": 70, "Water": 30, "H": 10}, "outputs": {"Au": 5}, "bonus": [], "xp": 100, "level_req": 48, "duration": 20.0, "category": "misc", "research_req": "industrial_electrolysis"},
	"craft_adv_circuit": {"name": "Advanced Circuitry", "inputs": {"Semiconductor": 1, "Au": 1}, "outputs": {"AdvCircuit": 1}, "bonus": [], "xp": 80, "level_req": 45, "duration": 15.0, "category": "misc", "research_req": "automation"},
	"craft_chip": {"name": "Chip Fabrication", "inputs": {"Semiconductor": 2, "Au": 1, "N": 5}, "outputs": {"Chip": 1}, "bonus": [], "xp": 60, "level_req": 40, "duration": 20.0, "category": "misc", "research_req": "adv_materials"},
	"craft_battery_t1": {"name": "Assemble Basic Battery", "inputs": {"Li": 5, "Fe": 2}, "outputs": {"BatteryT1": 1}, "bonus": [], "xp": 60, "level_req": 6, "duration": 10.0, "category": "misc", "research_req": "power_systems"},
	"craft_battery_t2": {"name": "Graphene Matrix Battery", "inputs": {"BatteryT1": 10, "Chip": 5, "Graphite": 5, "AdvCircuit": 5}, "outputs": {"BatteryT2": 1}, "bonus": [], "xp": 200, "level_req": 55, "duration": 20.0, "category": "misc", "research_req": "adv_materials"},
	"craft_battery_t3": {"name": "Zero-Point Module", "inputs": {"BatteryT2": 1, "VoidArtifact": 1, "Circuit": 20}, "outputs": {"BatteryT3": 1}, "bonus": [], "xp": 800, "level_req": 80, "duration": 60.0, "category": "misc", "research_req": "warp_drive"},
	"smelt_bauxite": {"name": "Bauxite Smelting", "inputs": {"Bauxite": 3, "O": 2}, "outputs": {"Al": 2}, "bonus": [], "xp": 15, "level_req": 16, "duration": 3.0, "category": "misc", "research_req": "basic_engineering"},
	"process_dolomite": {"name": "Dolomite Calcination", "inputs": {"Dolomite": 4, "C": 1}, "outputs": {"Mg": 1}, "bonus": [], "xp": 15, "level_req": 15, "duration": 6.0, "category": "misc", "research_req": "combustion"},
	"craft_cobalt_battery": {"name": "Lithium-Cobalt Battery", "inputs": {"Li": 2, "Co": 3, "Al": 2, "Circuit": 1}, "outputs": {"CoBattery": 1}, "bonus": [], "xp": 100, "level_req": 15, "duration": 10.0, "category": "misc", "research_req": "advanced_batteries"},
	"craft_mg_ion_battery": {"name": "Magnesium-Ion Battery", "inputs": {"Mg": 4, "Mn": 2, "AlWire": 2}, "outputs": {"MgBattery": 1}, "bonus": [], "xp": 80, "level_req": 14, "duration": 8.0, "category": "misc", "research_req": "advanced_batteries"},
	"electrolysis_nickel_catalyst": {"name": "Nickel-Catalyzed Electrolysis", "inputs": {"Water": 10, "Ni": 1}, "outputs": {"H": 30, "O": 20}, "bonus": [], "xp": 300, "level_req": 12, "duration": 20.0, "category": "misc", "research_req": "catalytic_electrodes"},
	"craft_superalloy": {"name": "Superalloy", "inputs": {"Fe": 2, "Al": 2, "Co": 2, "Ni": 2, "Cr": 1, "Ti": 1}, "outputs": {"Superalloy": 1}, "bonus": [], "xp": 200, "level_req": 18, "duration": 10.0, "category": "misc", "research_req": "superalloy_engineering"},
	"craft_platinum_catalyst": {"name": "Platinum Catalyst Matrix", "inputs": {"Pt": 10, "Si": 50, "AdvCircuit": 5}, "outputs": {"PtCatalyst": 1}, "bonus": [], "xp": 300, "level_req": 25, "duration": 20.0, "category": "misc", "research_req": "industrial_catalysis"},
	"craft_silver_catalyst": {"name": "Silver Catalyst", "inputs": {"Ag": 10, "Si": 20, "Circuit": 5}, "outputs": {"AgCatalyst": 1}, "bonus": [], "xp": 150, "level_req": 30, "duration": 15.0, "category": "misc", "research_req": "industrial_catalysis"},
	"craft_magnet": {"name": "Superconducting Magnet", "inputs": {"Sn": 20, "Fe": 10, "Cu": 10}, "outputs": {"SuperconductingMagnet": 1}, "bonus": [], "xp": 200, "level_req": 35, "duration": 15.0, "category": "misc", "research_req": "metallurgy_advanced"},
	"craft_palladium_cell": {"name": "Palladium Fuel Cell", "inputs": {"Pd": 5, "H": 20, "Circuit": 3}, "outputs": {"PdFuelCell": 1}, "bonus": [], "xp": 100, "level_req": 30, "duration": 15.0, "category": "misc", "research_req": "fuel_cell_tech"},
	"craft_iridium_plate": {"name": "Iridium Armor Plating", "inputs": {"Ir": 8, "Ti": 20, "Graphite": 10}, "outputs": {"IrPlate": 5}, "bonus": [], "xp": 400, "level_req": 28, "duration": 25.0, "category": "misc", "research_req": "iridium_metallurgy"},
	"craft_osmium_core": {"name": "Osmium Reactor Core", "inputs": {"Os": 5, "VoidCrystal": 2, "QuantumCore": 1}, "outputs": {"OsCore": 1}, "bonus": [], "xp": 800, "level_req": 30, "duration": 30.0, "category": "misc", "research_req": "exotic_metallurgy"},
	"refine_platinum_ore": {"name": "Platinum Extraction", "inputs": {"PtOre": 10}, "outputs": {"Pt": 2}, "bonus": [["Pd", 0.3, 1, 2]], "xp": 100, "level_req": 20, "duration": 8.0, "category": "misc", "research_req": "precious_metal_refining"},
	"craft_iridium_tungsten_alloy": {"name": "Iridium-Tungsten Alloy", "inputs": {"Ir": 3, "W": 5}, "outputs": {"IrWAlloy": 4}, "bonus": [], "xp": 250, "level_req": 26, "duration": 12.0, "category": "misc", "research_req": "iridium_metallurgy"},
	"craft_void_battery": {"name": "Void Battery", "inputs": {"VoidEssence": 10, "ExoticMatter": 5, "QuantumCore": 2}, "outputs": {"VoidBattery": 1}, "bonus": [], "xp": 2000, "level_req": 80, "duration": 60.0, "category": "endgame", "research_req": "exotic_metallurgy"},
	"craft_temporal_module": {"name": "Temporal Stabilizer", "inputs": {"ChronoCore": 5, "QuantumCore": 10, "AdvCircuit": 20}, "outputs": {"TemporalModule": 1}, "bonus": [], "xp": 3000, "level_req": 85, "duration": 90.0, "category": "endgame", "research_req": "exotic_metallurgy"},
	"craft_primordial_armor": {"name": "Primordial Forge", "inputs": {"PrimordialShard": 3, "OmegaPlating": 10, "IrPlate": 5}, "outputs": {"PrimordialArmor": 1}, "bonus": [], "xp": 5000, "level_req": 90, "duration": 120.0, "category": "endgame", "research_req": "exotic_metallurgy"},
	"craft_omega_accelerator": {"name": "Omega Accelerator", "inputs": {"OmegaPlating": 5, "ChronoCore": 3, "VoidEssence": 5, "QuantumCore": 5}, "outputs": {"OmegaAccelerator": 1}, "bonus": [], "xp": 10000, "level_req": 95, "duration": 180.0, "category": "endgame", "research_req": "exotic_metallurgy"},
	"distill_void_essence": {"name": "Void Distillation", "inputs": {"VoidEssence": 20}, "outputs": {"ExoticMatter": 10}, "bonus": [], "xp": 1500, "level_req": 75, "duration": 45.0, "category": "endgame", "research_req": "exotic_matter_analysis"},
	"synthesize_bioweapon": {"name": "Bio-Agent Synthesis", "inputs": {"BiohazardSample": 10, "PathogenCore": 2, "MutatedTissue": 5}, "outputs": {"BioWeaponCoating": 3}, "bonus": [], "xp": 1200, "level_req": 70, "duration": 30.0, "category": "endgame", "research_req": "quarantine_protocols"},
	"craft_ai_processor": {"name": "AI Processor Array", "inputs": {"AIMatrix": 2, "AdvCircuit": 20, "QuantumCore": 1}, "outputs": {"AIProcessor": 1}, "bonus": [], "xp": 1800, "level_req": 75, "duration": 45.0, "category": "endgame", "research_req": "quarantine_protocols"},
	"craft_regenerative_plating": {"name": "Regenerative Hull Plating", "inputs": {"MutatedTissue": 10, "IrPlate": 3, "PathogenCore": 1}, "outputs": {"RegenPlating": 2}, "bonus": [], "xp": 1500, "level_req": 72, "duration": 40.0, "category": "endgame", "research_req": "quarantine_protocols"},
	"purify_biohazard": {"name": "Pathogen Purification", "inputs": {"BiohazardSample": 20}, "outputs": {"PurifiedCompound": 5}, "bonus": [["PathogenCore", 0.2, 1, 1]], "xp": 800, "level_req": 65, "duration": 20.0, "category": "endgame", "research_req": "quarantine_protocols"},
	"decode_manifest": {"name": "Decode Pirate Manifest", "inputs": {"PirateManifest": 1}, "outputs": {"NavData": 1}, "bonus": [], "xp": 30, "level_req": 15, "duration": 15.0, "category": "salvage"},
	"process_colony_salvage": {"name": "Process Colony Salvage", "inputs": {"ColonySalvage": 10, "Circuit": 5}, "outputs": {"AdvCircuit": 3}, "bonus": [], "xp": 150, "level_req": 40, "duration": 30.0, "category": "salvage", "research_req": "deep_space_nav"},
	"process_rad_isotope": {"name": "Refine Radioactive Isotopes", "inputs": {"RadIsotope": 5, "H": 20, "Steel": 10}, "outputs": {"NuclearFuel": 2}, "bonus": [], "xp": 200, "level_req": 55, "duration": 45.0, "category": "endgame", "research_req": "radiation_shielding"},
	"decode_ancient_tech": {"name": "Decode Ancient Technology", "inputs": {"AncientTech": 3, "VoidArtifact": 5}, "outputs": {"QuantumCore": 2}, "bonus": [], "xp": 500, "level_req": 70, "duration": 90.0, "category": "endgame", "research_req": "exotic_matter_analysis"},
	"fence_stolen_cargo": {"name": "Fence Stolen Cargo", "inputs": {"StolenCargo": 1}, "outputs": {}, "bonus": [["NavData", 0.3, 1, 2], ["Chip", 0.2, 1, 1], ["Ti", 0.25, 5, 15], ["W", 0.15, 5, 10]], "xp": 20, "level_req": 10, "duration": 10.0, "category": "salvage"},
	"assemble_drone_core": {"name": "Assemble Drone Core", "inputs": {"SwarmFragment": 5, "Si": 5}, "outputs": {"DroneCore": 2}, "bonus": [], "xp": 25, "level_req": 8, "duration": 15.0, "category": "salvage"},
	"craft_cryo_coolant": {"name": "Cryogenic Coolant", "inputs": {"CryoCell": 1, "Water": 5}, "outputs": {"NitroCoolant": 1}, "bonus": [], "xp": 30, "level_req": 20, "duration": 10.0, "category": "processing"},
	"craft_turret_targeting": {"name": "Salvage Targeting Array", "inputs": {"TurretCore": 2, "Circuit": 10}, "outputs": {"TargetingChip": 1}, "bonus": [], "xp": 100, "level_req": 45, "duration": 20.0, "category": "salvage", "research_req": "deep_space_nav"},
}

const RESEARCH := {
	"basic_engineering": {"name": "Basic Engineering", "desc": "Unlocks: · • Mineral Washing · • Scrap Recycling · • Lithium Refining", "credits": 125, "items": {}, "parent": ""},
	"applied_physics": {"name": "Applied Physics", "desc": "Unlocks: Energy Fields, Sensor Calibration (Operations), Reactor Overclocking (Ships)", "credits": 625, "items": {}, "parent": "basic_engineering"},
	"materials_science": {"name": "Materials Science", "desc": "Unlocks: · • Advanced Technologies", "credits": 625, "items": {}, "parent": "basic_engineering"},
	"industrial_logistics": {"name": "Industrial Logistics", "desc": "Unlocks: · • Advanced Technologies", "credits": 625, "items": {}, "parent": "basic_engineering"},
	"fluid_dynamics": {"name": "Fluid Dynamics", "desc": "Unlocks: · • Water Pumping · • Electrolysis · • High-Flow Pumps (Operations)", "credits": 125, "items": {}, "parent": "applied_physics"},
	"combustion": {"name": "Organic Combustion", "desc": "Unlocks: · • Charcoal Kiln · • Fly Ash Separation · • HE Missile (Ammo) · • Micro-Missile Launcher · • Laser Cutters (Operations) · • Carbon Hull Lattice (Ships)", "credits": 125, "items": {}, "parent": "materials_science"},
	"smelting": {"name": "Efficient Smelting", "desc": "Unlocks: · • Steel Foundry · • Galvanized Steel · • Shipwright I, Processing Tungsten, Salvage Heuristics (Ships)", "credits": 3750, "items": {"Res1": 7, "Circuit": 15}, "parent": "combustion"},
	"shipwright_1": {"name": "Shipwright I", "desc": "Unlocks: · • Industrial Frigate  · • Titanium Plating · • Sector Scanning, Asteroid Belt Clearance (Operations) · • [Requires: Efficient Smelting (Engineering)]", "credits": 50000, "items": {"Steel": 50, "Res1": 20, "Circuit": 10}, "parent": "power_systems"},
	"shipwright_2": {"name": "Shipwright II", "desc": "Unlocks: · • Destroyer Class", "credits": 1000000, "items": {"Res2": 100}, "parent": "shipwright_1"},
	"adv_materials": {"name": "Advanced Materials", "desc": "Unlocks: · • Graphite Press · • Factory Automation branch · • Hydraulic Press branch", "credits": 5000, "items": {"Res2": 5}, "parent": "smelting"},
	"energy_shields": {"name": "Energy Fields", "desc": "Unlocks: · • Deflector Shield · • Shield Harmonics (Ships) · • [Requires: Applied Physics (Engineering)]", "credits": 1250, "items": {}, "parent": "eff_scanning_1"},
	"field_theory": {"name": "Field Theory", "desc": "Unlocks: · • Stasis Web", "credits": 37500, "items": {"Res2": 15}, "parent": "energy_shields"},
	"eff_scanning_1": {"name": "Sensor Calibration", "desc": "Bonus: +50% Scanning Yield · • [Requires: Applied Physics (Engineering)]", "credits": 375, "items": {}, "parent": ""},
	"automation": {"name": "Factory Automation", "desc": "Unlocks: · • Advanced Circuit · • Automated Assembly Line · • Advanced Rocketry (Ships)", "credits": 12500, "items": {"Res2": 25, "Circuit": 20}, "parent": "adv_materials"},
	"advanced_rocketry": {"name": "Advanced Rocketry", "desc": "Unlocks: · • Seeker Missile Mk.II · • Seeker Missile (Ammo) · • [Requires: Factory Automation (Engineering)]", "credits": 37500, "items": {"Steel": 100, "Circuit": 50}, "parent": "automation"},
	"sector_alpha_decryption": {"name": "Sector Scanning (Alpha)", "desc": "Unlocks: · • Sector Alpha · • [Requires: Outer System Authorization]", "credits": 50000, "items": {"NavData": 10, "PirateManifest": 10}, "parent": "outer_system_auth"},
	"advanced_batteries": {"name": "Advanced Battery Tech", "desc": "Unlocks: · • Cobalt-Lithium Battery · • Magnesium-Ion Cell · • [Requires: Advanced Materials (Engineering)]", "credits": 7500, "items": {"Co": 25, "Mg": 25, "Li": 25}, "parent": "adv_materials"},
	"xeno_archaeology": {"name": "Xeno-Archaeology", "desc": "Unlocks: · • Analyze Void Artifact", "credits": 5000, "items": {"VoidArtifact": 1, "NavData": 5}, "parent": "sector_alpha_decryption"},
	"warp_drive": {"name": "Warp Drive Theory", "desc": "Unlocks: · • Galaxy Map · • Deep Space Navigation (Operations)", "credits": 12500, "items": {"NavData": 50, "Ti": 200, "Res3": 10}, "parent": "shipwright_2"},
	"asteroid_clearance": {"name": "Asteroid Belt Clearance", "desc": "Unlocks: · • Asteroid Belt zone · • Claim Jumper enemy · • [Requires: Shipwright I (Ships)]", "credits": 6250, "items": {"Cu": 10, "W": 5}, "parent": "eff_scanning_1"},
	"mars_license": {"name": "Mars Sector License", "desc": "Unlocks: · • Mars Debris Field zone · • Derelict Frigate enemy", "credits": 25000, "items": {"StolenCargo": 5, "NavData": 5, "Steel": 50}, "parent": "asteroid_clearance"},
	"outer_system_auth": {"name": "Outer System Authorization", "desc": "Unlocks: · • Titan's Halo zone · • Pirate Gunship enemy", "credits": 62500, "items": {"Res2": 10, "Steel": 100, "Circuit": 20}, "parent": "mars_license"},
	"deep_space_expedition": {"name": "Deep Space Expedition", "desc": "Unlocks: · • [Requires: Outer System Authorization] · • Prerequisite for Sector Zeta access", "credits": 250000, "items": {"VoidArtifact": 3, "Res3": 25, "AdvCircuit": 25}, "parent": "outer_system_auth"},
	"quarantine_protocols": {"name": "Quarantine Protocols", "desc": "Unlocks: · • Sector Zeta zone · • [Requires: Deep Space Expedition]", "credits": 150000, "items": {"Res3": 40, "VoidCrystal": 10, "AdvCircuit": 30}, "parent": "deep_space_expedition"},
	"kinetics_101": {"name": "Kinetic Weapons Theory", "desc": "Unlocks: · • Mass Driver · • [Requires: Applied Physics (Engineering)]", "credits": 50, "items": {}, "parent": ""},
	"laser_optics": {"name": "Laser Optics", "desc": "Unlocks: · • Pulse Laser Mk.II", "credits": 300, "items": {"Res1": 5}, "parent": "power_systems"},
	"power_systems": {"name": "Power Systems", "desc": "Unlocks: · • Basic Battery Module · • [Requires: Applied Physics (Engineering)]", "credits": 300, "items": {}, "parent": "kinetics_101"},
	"lightweight_alloys": {"name": "Lightweight Alloys", "desc": "Unlocks: · • Aluminum Smelting · • Aluminum-Magnesium Alloy", "credits": 200, "items": {"Res1": 3}, "parent": "materials_science"},
	"basic_electronics": {"name": "Basic Electronics", "desc": "Unlocks: · • Standard Circuit Assembly (Industrial)", "credits": 800, "items": {"Cu": 20, "Si": 20}, "parent": "industrial_logistics"},
	"diamond_drills": {"name": "Diamond Tipped Drills", "desc": "Bonus: · • +25% Excavate Soil speed · • [Requires: Industrial Logistics (Engineering)]", "credits": 200, "items": {"Res1": 2}, "parent": ""},
	"high_flow_pumps": {"name": "High-Flow Pumps", "desc": "Bonus: · • +50% Pump Water speed · • [Requires: Fluid Dynamics (Engineering)]", "credits": 250, "items": {"Res1": 2}, "parent": ""},
	"laser_cutters": {"name": "Laser Cutters", "desc": "Bonus: · • +50% Deforest Zone speed · • [Requires: Organic Combustion (Engineering)]", "credits": 300, "items": {"Res1": 2}, "parent": ""},
	"magnetic_funnels": {"name": "Magnetic Funnels", "desc": "Bonus: · • +25% Harvest Nebula speed", "credits": 2000, "items": {}, "parent": "energy_shields"},
	"ultrasonic_drills": {"name": "Ultrasonic Drills", "desc": "Bonus: · • +50% Excavate Soil speed", "credits": 1000, "items": {"Res1": 250}, "parent": "diamond_drills"},
	"plasma_bore": {"name": "Plasma Bore", "desc": "Bonus: · • +75% Excavate Soil speed", "credits": 5000, "items": {"Res2": 20}, "parent": "ultrasonic_drills"},
	"superfluid_intake": {"name": "Superfluid Intake", "desc": "Bonus: · • +50% Pump Water speed", "credits": 1500, "items": {"Res2": 15}, "parent": "high_flow_pumps"},
	"hydro_vortex": {"name": "Hydro-Vortex Arrays", "desc": "Bonus: · • +75% Pump Water speed", "credits": 7500, "items": {"Res3": 5, "AdvCircuit": 10}, "parent": "superfluid_intake"},
	"mono_filament": {"name": "Mono-Filament Wire", "desc": "Bonus: · • +50% Deforest Zone speed", "credits": 2000, "items": {"Res2": 15}, "parent": "laser_cutters"},
	"molecular_disassembler": {"name": "Molecular Disassembler", "desc": "Bonus: · • +75% Deforest Zone speed", "credits": 10000, "items": {"Res3": 10, "AdvCircuit": 15}, "parent": "mono_filament"},
	"fast_centrifuges": {"name": "High-RPM Centrifuges", "desc": "Bonus: · • +25% Mineral Washing speed", "credits": 200, "items": {}, "parent": "industrial_logistics"},
	"catalytic_electrodes": {"name": "Catalytic Electrodes", "desc": "Bonus: · • +25% Electrolysis speed", "credits": 300, "items": {}, "parent": "fluid_dynamics"},
	"pyrolysis_control": {"name": "Pyrolysis Control", "desc": "Bonus: · • +25% Charcoal Kiln speed", "credits": 400, "items": {"Res1": 5}, "parent": "combustion"},
	"blast_furnace": {"name": "Blast Furnace", "desc": "Bonus: · • +25% Steel Foundry speed", "credits": 800, "items": {"Res1": 10}, "parent": "smelting"},
	"hydraulic_press": {"name": "Hydraulic Press", "desc": "Bonus: · • +25% Graphite Press speed", "credits": 1500, "items": {"Res1": 10}, "parent": "adv_materials"},
	"maglev_bearings": {"name": "Mag-Lev Bearings", "desc": "Bonus: · • +50% Mineral Washing speed", "credits": 1000, "items": {"Res2": 15}, "parent": "fast_centrifuges"},
	"quantum_separators": {"name": "Quantum Separators", "desc": "Bonus: · • +75% Mineral Washing speed", "credits": 5000, "items": {"Res3": 10, "AdvCircuit": 10}, "parent": "maglev_bearings"},
	"advanced_mineralogy": {"name": "Advanced Mineralogy", "desc": "Industrial Centrifuges now have a chance to extract Titanium (Ti) from Dirt processing.", "credits": 5000, "items": {"Si": 100, "Fe": 100}, "parent": "fast_centrifuges"},
	"ion_exchange": {"name": "Ion-Exchange Membranes", "desc": "Bonus: · • +50% Electrolysis speed", "credits": 1500, "items": {"Res2": 15}, "parent": "catalytic_electrodes"},
	"resonance_splitters": {"name": "Resonance Splitters", "desc": "Bonus: · • +75% Electrolysis speed", "credits": 7500, "items": {"Res3": 10, "AdvCircuit": 10}, "parent": "ion_exchange"},
	"processing_tungsten": {"name": "Processing Tungsten", "desc": "Unlocks: · • Tungsten Sabot Rounds (T2) · • [Requires: Efficient Smelting (Engineering)]", "credits": 1000, "items": {"Res1": 10}, "parent": "smelting"},
	"ballistics_optimization": {"name": "Ballistics Optimization", "desc": "Unlocks: · • Depleted Uranium Rounds (T3) · • Heavy Railgun", "credits": 1500, "items": {"Res2": 15}, "parent": "processing_tungsten"},
	"energy_metrics": {"name": "Energy Metrics", "desc": "Unlocks: · • Hydrogen Reactor · • Vaporizer Cells (T3) · • Plasma Lance Mk.III · • Orbital Gas Siphon (Auto) · • Uranium Centrifuge (Auto)", "credits": 5000, "items": {"Res2": 20, "AdvCircuit": 10}, "parent": "fluid_dynamics"},
	"cryogenic_systems": {"name": "Cryogenic Systems", "desc": "Unlocks: · • Helium Coolant Cell · • Cryo-Cooled Laser Mk.III", "credits": 25000, "items": {"He": 50, "Ti": 30}, "parent": "energy_metrics"},
	"automated_logistics": {"name": "Automated Logistics", "desc": "Unlocks: · • Drone Bay · • Fleet Logistics I (Ships)", "credits": 3000, "items": {"Cu": 100, "Fe": 100}, "parent": "industrial_logistics"},
	"molecular_printing": {"name": "Molecular Printing", "desc": "Unlocks: · • Fabricator (+20% crafting)", "credits": 5000, "items": {"Circuit": 50, "Fiber": 20}, "parent": "shipwright_2"},
	"automated_smelting": {"name": "Automated Smelting", "desc": "Unlocks: · • Auto-Smelter", "credits": 2500, "items": {"Ti": 20}, "parent": "blast_furnace"},
	"oxygen_blast_furnace": {"name": "Oxygen-Blast Furnaces", "desc": "Increases Steel yield from 1 to 5 per cycle.", "credits": 5000, "items": {"Steel": 100, "O": 200}, "parent": "blast_furnace"},
	"industrial_electrolysis": {"name": "Industrial Electrolysis", "desc": "Unlocks: · • Hydro-Plant", "credits": 2500, "items": {"Si": 50}, "parent": "catalytic_electrodes"},
	"molecular_compression": {"name": "Molecular Compression", "desc": "Unlocks: · • Auto-Press", "credits": 3000, "items": {"Fe": 100}, "parent": "hydraulic_press"},
	"mass_production_tactics": {"name": "Mass Production Tactics", "desc": "Unlocks: · • Munitions Factory", "credits": 5000, "items": {"Circuit": 20, "Steel": 20}, "parent": "automated_logistics"},
	"xeno_engineering": {"name": "Xeno-Engineering", "desc": "Unlocks: · • Alien Flora Cultivation · • Analyzing Xeno-Materials", "credits": 10000, "items": {"SalvageData": 10, "Circuit": 50}, "parent": "automated_logistics"},
	"fleet_logistics_1": {"name": "Fleet Logistics I", "desc": "Unlocks: · • Secondary Fleet Slot · • Basic Expeditionary Command · • [Requires: Automated Logistics (Engineering)]", "credits": 25000, "items": {"Circuit": 100, "Ti": 100}, "parent": "warp_drive"},
	"fleet_logistics_2": {"name": "Fleet Logistics II", "desc": "Unlocks: · • Tertiary Fleet Slot · • Advanced Fleet Coordination", "credits": 250000, "items": {"AdvCircuit": 50, "Gold": 20}, "parent": "fleet_logistics_1"},
	"automated_expeditions": {"name": "Predictive Route Planning", "desc": "Bonus: · • -25% Fleet Mission Interval", "credits": 50000, "items": {"NavData": 50, "Circuit": 200}, "parent": "fleet_logistics_1"},
	"capital_ship_engineering": {"name": "Capital Ship Doctrine", "desc": "Unlocks: · • Battlecruiser Class  · • Coil Cannon · • Antimatter Engine", "credits": 500000, "items": {"VoidArtifact": 20, "NavData": 75, "Res3": 75}, "parent": "shipwright_2"},
	"capital_ship_armament": {"name": "Capital Ship Armament", "desc": "Unlocks: · • Heavy Torpedo Launcher · • Photon Torpedo (Ammo)", "credits": 1000000, "items": {"VoidArtifact": 10, "Superalloy": 50, "AdvCircuit": 50}, "parent": "capital_ship_engineering"},
	"quantum_dynamics": {"name": "Quantum Dynamics", "desc": "Unlocks: · • Dreadnought Class ", "credits": 5000000, "items": {"QuantumCore": 20, "VoidArtifact": 50, "ColonyDataCore": 50, "RadIsotope": 1000, "Res3": 500, "ExoticIsotope": 20}, "parent": "capital_ship_engineering"},
	"broadside_tactics": {"name": "Broadside Tactics", "desc": "Unlocks: · • Broadside Integrated Array (Burst Module)", "credits": 250000, "items": {"Res3": 25, "AdvCircuit": 50, "TurretCore": 1}, "parent": "capital_ship_engineering"},
	"deep_space_nav": {"name": "Deep Space Navigation", "desc": "Unlocks: · • Sector Beta (Mining Colony) · • Precious Metal Refining, Colony AI Integration (Engineering) · • [Requires: Warp Drive Theory (Ships)]", "credits": 100000, "items": {"NavData": 25, "Ti": 150, "Res3": 10}, "parent": ""},
	"radiation_shielding": {"name": "Radiation Shielding Theory", "desc": "Unlocks: · • Sector Gamma (Radioactive) · • High-Energy Gamma Optics (Ships)", "credits": 250000, "items": {"Co": 50, "Al": 100, "Superalloy": 25, "AdvCircuit": 15}, "parent": "deep_space_nav"},
	"exotic_matter_analysis": {"name": "Exotic Matter Analysis", "desc": "Unlocks: · • Sector Delta (Crystalline)", "credits": 1000000, "items": {"Pt": 20, "RadIsotope": 50, "QuantumCore": 3}, "parent": "radiation_shielding"},
	"efficiency_1": {"name": "Efficiency I", "desc": "Yield Bonus: · • x2 Output (Gathering & Processing)", "credits": 250000, "items": {"Circuit": 250, "Steel": 500, "Res1": 1000, "Res2": 100}, "parent": "industrial_logistics"},
	"efficiency_2": {"name": "Efficiency II", "desc": "Yield Bonus: · • x4 Output (Gathering & Processing)", "credits": 1000000, "items": {"AdvCircuit": 100, "Ti": 1000, "Res3": 50}, "parent": "efficiency_1"},
	"efficiency_3": {"name": "Efficiency III", "desc": "Yield Bonus: · • x8 Output (Gathering & Processing)", "credits": 5000000, "items": {"QuantumCore": 10, "U": 500, "Platinum": 250}, "parent": "efficiency_2"},
	"efficiency_4": {"name": "Efficiency IV", "desc": "Yield Bonus: · • x16 Output (Gathering & Processing)", "credits": 25000000, "items": {"ExoticMatter": 5, "Osmium": 100, "VoidCrystal": 50}, "parent": "efficiency_3"},
	"efficiency_5": {"name": "Efficiency V", "desc": "Yield Bonus: · • x32 Output (Gathering & Processing)", "credits": 100000000, "items": {"ExoticIsotope": 25, "Neutronium": 5, "QuantumCore": 50}, "parent": "efficiency_4"},
	"metallurgy_advanced": {"name": "Advanced Metallurgy", "desc": "Unlocks: · • Stainless Steel Alloy", "credits": 5000, "items": {"Ni": 100}, "parent": "smelting"},
	"superalloy_engineering": {"name": "Superalloy Engineering", "desc": "Unlocks: · • Superalloy", "credits": 100000, "items": {"Co": 100, "Ni": 100, "Cr": 50, "Ti": 100}, "parent": "metallurgy_advanced"},
	"precious_metal_refining": {"name": "Precious Metal Refining", "desc": "Unlocks: · • Platinum Extraction · • Palladium Refining · • Precious Metal Dredge · • [Requires: Deep Space Navigation (Operations)]", "credits": 15000, "items": {"Ti": 200, "Res2": 25}, "parent": ""},
	"industrial_catalysis": {"name": "Industrial Catalysis", "desc": "Bonus: · • +25% All Production Speed", "credits": 1000000, "items": {"Pt": 200, "Si": 200, "AdvCircuit": 20}, "parent": "precious_metal_refining"},
	"fuel_cell_tech": {"name": "Fuel Cell Technology", "desc": "Unlocks: · • Hydrogen Fuel Cell", "credits": 250000, "items": {"Pd": 30, "H": 500, "Circuit": 30}, "parent": "precious_metal_refining"},
	"iridium_metallurgy": {"name": "Iridium Metallurgy", "desc": "Unlocks: · • Iridium Extraction · • Iridium Armor Plating", "credits": 40000, "items": {"Pt": 50, "Res3": 10}, "parent": "superalloy_engineering"},
	"exotic_metallurgy": {"name": "Exotic Metallurgy", "desc": "Unlocks: · • Osmium Harvesting · • Osmium Armor Plating", "credits": 2000000, "items": {"Ir": 100, "Res3": 50}, "parent": "iridium_metallurgy"},
	"colony_automation": {"name": "Colony AI Integration", "desc": "Unlocks: · • Colonial Auto-Extractor (Grants +5 Base Gathering Yield) · • [Requires: Deep Space Navigation (Operations)]", "credits": 50000, "items": {"ColonyDataCore": 1, "ColonySalvage": 100, "AdvCircuit": 50}, "parent": ""},
	"gamma_optics": {"name": "High-Energy Gamma Optics", "desc": "Unlocks: · • Gamma Pulse Battery (Ship Module) · • Advanced Laser Tech · • [Requires: Radiation Shielding Theory (Operations)]", "credits": 75000, "items": {"RadIsotope": 50, "Pt": 100}, "parent": "advanced_rocketry"},
	"void_physics": {"name": "Extreme Void Physics", "desc": "Unlocks: · • Void Phase Engine (Ship Module) · • Void Shielding", "credits": 5000000, "items": {"VoidCrystal": 20, "QuantumCore": 10, "AntimatterParticle": 5}, "parent": "exotic_matter_analysis"},
	"void_navigation": {"name": "Void Navigation", "desc": "Unlocks: · • Sector Epsilon - The Void · • Void Rift Anchor (Auto) · • Chrono-Siphon (Auto) · • Void Weaponry/Shielding Optimization (Ships)", "credits": 50000000, "items": {"QuantumCore": 30, "VoidCrystal": 50, "ExoticMatter": 20, "AncientTech": 5, "QuarantineClearance": 1, "BiohazardSample": 20}, "parent": "void_physics"},
	"void_weaponry_1": {"name": "Void Weaponry Optimization", "desc": "Bonus: · • +20% Total Ship Damage · • [Requires: Void Navigation (Operations)]", "credits": 100000000, "items": {"VoidEssence": 50, "ChronoCore": 20, "PrimordialShard": 5, "MutatedTissue": 10, "BioWeaponCoating": 10}, "parent": ""},
	"void_shielding_1": {"name": "Void Shielding Optimization", "desc": "Bonus: · • +20% Total Ship Shields · • [Requires: Void Navigation (Operations)]", "credits": 100000000, "items": {"OmegaPlating": 50, "VoidEssence": 20, "PrimordialShard": 5, "Os": 25, "MutatedTissue": 10, "RegenPlating": 8}, "parent": ""},
	"perfect_automation": {"name": "Omni-Fabrication", "desc": "Bonus: · • +30% Processing & Research Speed (Global)", "credits": 10000000, "items": {"AICore": 5, "AncientTech": 5, "AdvCircuit": 200, "AIProcessor": 5}, "parent": "colony_automation"},
	"salvage_heuristics": {"name": "Salvage Heuristics", "desc": "Bonus: · • +2 rolls in Scrap Recycling · • [Requires: Efficient Smelting (Engineering)]", "credits": 1000, "items": {"Res1": 10}, "parent": "smelting"},
	"scavenger_protocol": {"name": "Scavenger Protocol", "desc": "Bonus: · • +15% DroneCore drop chance", "credits": 2500, "items": {"Res2": 5}, "parent": "salvage_heuristics"},
	"combat_heuristics": {"name": "Combat Heuristics", "desc": "Bonus: · • +20% Combat XP gain", "credits": 1500, "items": {"Res1": 10}, "parent": "industrial_logistics"},
	"shield_harmonics": {"name": "Shield Harmonics", "desc": "Bonus: · • +20% Shield Regeneration speed · • [Requires: Energy Fields (Operations)]", "credits": 2000, "items": {"Res1": 10}, "parent": "energy_shields"},
	"hull_hardening": {"name": "Carbon Hull Lattice", "desc": "Bonus: · • +15% Ship Max HP · • [Requires: Organic Combustion (Engineering)]", "credits": 1200, "items": {"Res1": 5, "MiteChitin": 50}, "parent": "shield_harmonics"},
	"core_overclocking": {"name": "Reactor Overclocking", "desc": "Bonus: · • +10% Combat Attack Speed · • [Requires: Applied Physics (Engineering)]", "credits": 4000, "items": {"Res2": 10}, "parent": "applied_physics"},
	"deep_core_optics": {"name": "Deep Core Optics", "desc": "Bonus: · • +1 Base Yield for all Gathering", "credits": 800, "items": {"Res1": 5}, "parent": "laser_cutters"},
	"nano_fabrication": {"name": "Nano-Fabrication", "desc": "Bonus: · • -15% Processing duration", "credits": 5000, "items": {"Res2": 10}, "parent": "automation"},
	"data_clustering": {"name": "Data Clustering", "desc": "Bonus: · • -20% Research action duration", "credits": 2000, "items": {"Res1": 15}, "parent": "industrial_logistics"},
	"industrial_automation": {"name": "Industrial Automation", "desc": "Unlocks: · • Electronics Assembler", "credits": 15000, "items": {"Circuit": 50, "Steel": 200}, "parent": "automated_smelting"},
	"molecular_recycling": {"name": "Molecular Recycling", "desc": "Unlocks: · • Matter De-constructor", "credits": 50000, "items": {"Res2": 50, "AdvCircuit": 25}, "parent": "industrial_automation"},
	"cryogenic_storage": {"name": "Cryogenic Storage", "desc": "Unlocks: · • Cryo-Storage Array", "credits": 30000, "items": {"Ti": 100, "Si": 200}, "parent": "cryogenic_systems"},
	"auto_repair_20": {"name": "Emergency Auto-Repair I", "desc": "Automatically uses equipped hull/shield consumables when integrity drops below 20%.", "credits": 5000, "items": {"Res1": 10, "MiteChitin": 25, "Mesh": 5}, "parent": "hull_hardening"},
	"auto_repair_40": {"name": "Emergency Auto-Repair II", "desc": "Increases auto-repair threshold to 40%.", "credits": 15000, "items": {"Res2": 5, "Seal": 10, "Mesh": 10}, "parent": "auto_repair_20"},
	"auto_repair_60": {"name": "Emergency Auto-Repair III", "desc": "Increases auto-repair threshold to 60%.", "credits": 50000, "items": {"Res2": 5, "AdvCircuit": 15}, "parent": "auto_repair_40"},
	"auto_repair_80": {"name": "Emergency Auto-Repair IV", "desc": "Increases auto-repair threshold to 80%.", "credits": 200000, "items": {"Res3": 3}, "parent": "auto_repair_60"},
}

const ENEMIES := {
	"dust_mite": {"name": "Space Dust Mite", "hp": 550, "atk": 45, "def": 10, "interval": 2.5, "loot": [["Fe", 1.0, 1, 3], ["MiteChitin", 1.0, 1, 1]], "xp": 8},
	"lunar_drone": {"name": "Lunar Drone", "hp": 850, "atk": 65, "def": 15, "interval": 2.5, "loot": [["Cu", 1.0, 2, 4], ["Fe", 1.0, 3, 6], ["DroneCore", 1.0, 1, 1]], "xp": 12},
	"scrap_collector": {"name": "Scrap Collector", "hp": 1100, "atk": 50, "def": 12, "interval": 2.2, "loot": [["Cu", 1.0, 5, 10], ["Res1", 1.0, 2, 5], ["DroneCore", 1.0, 2, 5]], "xp": 10},
	"survey_probe": {"name": "Survey Probe", "hp": 1400, "atk": 30, "def": 18, "interval": 1.0, "loot": [["credits", 1.0, 100, 250], ["Si", 1.0, 10, 20]], "xp": 25},
	"claim_jumper": {"name": "Claim Jumper", "hp": 4800, "atk": 155, "def": 38, "interval": 2.2, "loot": [["credits", 1.0, 250, 450], ["Cu", 1.0, 15, 30], ["StolenCargo", 1.0, 1, 1]], "xp": 50},
	"ore_hauler": {"name": "Ore Hauler Wreck", "hp": 7500, "atk": 220, "def": 45, "interval": 5.0, "loot": [["Fe", 1.0, 50, 70], ["W", 1.0, 15, 20]], "xp": 80},
	"derelict_frigate": {"name": "Derelict Frigate", "hp": 14500, "atk": 420, "def": 75, "interval": 4.0, "loot": [["Steel", 1.0, 5, 10], ["Fe", 1.0, 20, 40], ["Res2", 1.0, 5, 10]], "xp": 250},
	"salvage_swarm": {"name": "Salvage Swarm", "hp": 9500, "atk": 110, "def": 55, "interval": 0.6, "loot": [["Cu", 1.0, 10, 20], ["SwarmFragment", 1.0, 1, 2]], "xp": 35},
	"frozen_hulk": {"name": "Frozen Hulk", "hp": 38000, "atk": 1400, "def": 105, "interval": 6.0, "loot": [["C", 1.0, 10, 20]], "xp": 75},
	"smuggler_cutter": {"name": "Smuggler Cutter", "hp": 22000, "atk": 850, "def": 85, "interval": 2.0, "loot": [["credits", 1.0, 100, 200]], "xp": 95},
	"pirate_skiff": {"name": "Pirate Skiff", "hp": 5200, "atk": 165, "def": 42, "interval": 1.8, "loot": [["credits", 1.0, 2000, 6000], ["Fe", 1.0, 10, 20], ["PirateManifest", 1.0, 1, 1], ["NavData", 1.0, 1, 2], ["Cu", 1.0, 100, 200]], "xp": 30},
	"rock_golem": {"name": "Silicate Golem", "hp": 6500, "atk": 190, "def": 48, "interval": 2.0, "loot": [["Si", 1.0, 100, 200], ["Fe", 1.0, 10, 20]], "xp": 30},
	"scavenger_mech": {"name": "Scavenger Mech", "hp": 11500, "atk": 310, "def": 60, "interval": 2.0, "loot": [["Cu", 1.0, 10, 20]], "xp": 55},
	"martian_sentry": {"name": "Martian Sentry", "hp": 7500, "atk": 380, "def": 58, "interval": 2.0, "loot": [["C", 1.0, 5, 10]], "xp": 60},
	"cryo_drone": {"name": "Cryo Drone", "hp": 35000, "atk": 1250, "def": 95, "interval": 2.0, "loot": [["H", 1.0, 5, 15], ["Water", 1.0, 5, 10], ["CryoCell", 1.0, 1, 1]], "xp": 75},
	"pirate_gunship": {"name": "Pirate Gunship", "hp": 25000, "atk": 550, "def": 75, "interval": 2.0, "loot": [["credits", 1.0, 50, 150], ["Ti", 1.0, 1, 3]], "xp": 2500},
	"titan_overseer": {"name": "TITAN OVERSEER", "hp": 120000, "atk": 3500, "def": 180, "interval": 2.0, "loot": [["TitanClearance", 1.0, 1, 1], ["Ti", 1.0, 50, 100]], "xp": 15000},
	"alien_frigate": {"name": "Xenon Patrol Frigate", "hp": 60000, "atk": 1150, "def": 145, "interval": 2.0, "loot": [["credits", 1.0, 15000, 20000], ["Ti", 1.0, 30, 60]], "xp": 500},
	"xenon_corvette": {"name": "Xenon Corvette", "hp": 68000, "atk": 1350, "def": 150, "interval": 2.5, "loot": [["credits", 1.0, 40000, 60000], ["Superalloy", 1.0, 1, 2], ["VoidArtifact", 1.0, 2, 4], ["NavData", 1.0, 4, 8], ["Res3", 1.0, 2, 3], ["Ti", 1.0, 50, 100], ["U", 1.0, 5, 15]], "xp": 800},
	"xenon_mothership": {"name": "XENON MOTHERSHIP", "hp": 180000, "atk": 1800, "def": 120, "interval": 6.0, "loot": [["credits", 1.0, 700000, 1000000], ["Superalloy", 1.0, 30, 50], ["Chip", 1.0, 30, 50], ["AdvCircuit", 1.0, 10, 20], ["QuantumCore", 1.0, 5, 10], ["VoidArtifact", 1.0, 10, 25], ["Res3", 1.0, 50, 100]], "xp": 10000},
	"mining_sentinel": {"name": "Mining Sentinel MK-VII", "hp": 170000, "atk": 1750, "def": 120, "interval": 2.0, "loot": [["ColonySalvage", 1.0, 10, 20], ["Steel", 1.0, 50, 100]], "xp": 8000},
	"defense_turret": {"name": "Automated Defense Turret", "hp": 210000, "atk": 2100, "def": 135, "interval": 2.5, "loot": [["ColonySalvage", 1.0, 25, 50], ["Circuit", 1.0, 20, 50], ["TurretCore", 1.0, 1, 1]], "xp": 15000},
	"colony_overseer": {"name": "Colony Overseer AI", "hp": 250000, "atk": 2500, "def": 180, "interval": 3.5, "loot": [["AdvCircuit", 1.0, 20, 30], ["ColonySalvage", 1.0, 20, 40], ["ColonyDataCore", 1.0, 5, 7]], "xp": 35000},
	"radiation_beast": {"name": "Gamma Radiation Beast", "hp": 260000, "atk": 2400, "def": 180, "interval": 2.0, "loot": [["credits", 1.0, 750000, 1000000], ["RadIsotope", 1.0, 1, 3], ["U", 1.0, 100, 150]], "xp": 500},
	"nebula_leviathan": {"name": "Nebula Leviathan", "hp": 500000, "atk": 4500, "def": 250, "interval": 2.0, "loot": [["credits", 1.0, 3000000, 5000000], ["Pd", 1.0, 100, 200], ["RadIsotope", 1.0, 3, 5], ["U", 1.0, 700, 1000]], "xp": 60000},
	"gamma_colossus": {"name": "GAMMA COLOSSUS", "hp": 310000, "atk": 2850, "def": 190, "interval": 2.5, "loot": [["RadIsotope", 1.0, 50, 100], ["Pt", 1.0, 25, 50], ["QuantumCore", 1.0, 5, 10], ["ExoticIsotope", 1.0, 1, 3]], "xp": 30000},
	"crystal_golem": {"name": "Crystalline Golem", "hp": 550000, "atk": 4800, "def": 255, "interval": 2.0, "loot": [["VoidCrystal", 1.0, 1, 3], ["Si", 1.0, 50, 100], ["Diamond", 1.0, 1, 3]], "xp": 1500},
	"energy_wraith": {"name": "Energy Wraith", "hp": 480000, "atk": 5200, "def": 240, "interval": 2.0, "loot": [["ExoticMatter", 1.0, 2, 5], ["VoidCrystal", 1.0, 2, 4], ["H", 1.0, 20, 40]], "xp": 1800},
	"sentinel_prime": {"name": "SENTINEL PRIME", "hp": 1500000, "atk": 7500, "def": 500, "interval": 2.0, "loot": [["VoidCrystal", 1.0, 5, 10], ["Ir", 1.0, 10, 20], ["QuantumCore", 1.0, 2, 4]], "xp": 150000},
	"void_stalker": {"name": "Void Stalker", "hp": 1800000, "atk": 8500, "def": 550, "interval": 2.0, "loot": [["credits", 1.0, 100000, 200000], ["VoidCrystal", 1.0, 10, 20], ["ExoticMatter", 1.0, 5, 10]], "xp": 8000},
	"temporal_phantom": {"name": "Temporal Phantom", "hp": 2100000, "atk": 9500, "def": 580, "interval": 1.5, "loot": [["credits", 1.0, 150000, 300000], ["ExoticMatter", 1.0, 8, 15], ["VoidCrystal", 1.0, 5, 10], ["AntimatterParticle", 1.0, 1, 2]], "xp": 10000},
	"omega_sentinel": {"name": "OMEGA SENTINEL", "hp": 3500000, "atk": 16000, "def": 780, "interval": 2.0, "loot": [["credits", 1.0, 300000, 600000], ["VoidCrystal", 1.0, 20, 40], ["QuantumCore", 1.0, 5, 10], ["Ir", 1.0, 20, 40]], "xp": 25000},
	"primordial_titan": {"name": "★ PRIMORDIAL TITAN ★", "hp": 7500000, "atk": 24000, "def": 950, "interval": 5.0, "loot": [["credits", 1.0, 5000000, 15000000], ["VoidCrystal", 1.0, 100, 200], ["QuantumCore", 1.0, 20, 40], ["OmegaPlating", 1.0, 5, 10], ["PrimordialShard", 1.0, 1, 3], ["ChronoCore", 1.0, 2, 4], ["VoidEssence", 1.0, 5, 10]], "xp": 100000},
	"void_leviathan": {"name": "VOID LEVIATHAN", "hp": 15000000, "atk": 30000, "def": 1200, "interval": 6.0, "loot": [["credits", 1.0, 15000000, 30000000], ["VoidEssence", 1.0, 10, 20], ["PrimordialShard", 1.0, 5, 10]], "xp": 1000000},
	"plague_drone": {"name": "Plague Drone", "hp": 1600000, "atk": 8500, "def": 530, "interval": 1.8, "loot": [["credits", 1.0, 50000, 100000], ["BiohazardSample", 1.0, 2, 5], ["Ti", 1.0, 30, 60]], "xp": 3500},
	"bio_horror": {"name": "Bio-Horror", "hp": 1900000, "atk": 9800, "def": 560, "interval": 2.5, "loot": [["credits", 1.0, 80000, 150000], ["BiohazardSample", 1.0, 5, 10], ["MutatedTissue", 1.0, 2, 4]], "xp": 5000},
	"rogue_ai_core": {"name": "Rogue AI Core", "hp": 2400000, "atk": 10500, "def": 600, "interval": 1.5, "loot": [["credits", 1.0, 100000, 200000], ["AdvCircuit", 1.0, 10, 20], ["QuantumCore", 1.0, 1, 2]], "xp": 6000},
	"quarantine_warden": {"name": "QUARANTINE WARDEN", "hp": 3000000, "atk": 8500, "def": 900, "interval": 2.0, "loot": [["credits", 1.0, 200000, 400000], ["BiohazardSample", 1.0, 10, 20], ["PathogenCore", 1.0, 2, 4], ["MutatedTissue", 1.0, 5, 10]], "xp": 250000},
	"xenon_scout": {"name": "Xenon Scout", "hp": 55000, "atk": 1050, "def": 140, "interval": 1.5, "loot": [["credits", 1.0, 5000, 10000], ["Ti", 1.0, 10, 20], ["Fe", 1.0, 25, 50]], "xp": 350},
	"alien_probe": {"name": "Alien Probe", "hp": 65000, "atk": 1250, "def": 150, "interval": 2.0, "loot": [["credits", 1.0, 2000, 4000], ["SalvageData", 1.0, 2, 4], ["Circuit", 1.0, 3, 6]], "xp": 400},
	"repair_drone": {"name": "Repair Drone", "hp": 160000, "atk": 1650, "def": 125, "interval": 2.5, "loot": [["credits", 1.0, 3000, 6000], ["Cu", 1.0, 20, 40], ["Circuit", 1.0, 5, 10]], "xp": 500},
	"ore_guardian": {"name": "Ore Guardian", "hp": 190000, "atk": 1900, "def": 130, "interval": 2.0, "loot": [["Fe", 1.0, 100, 200], ["Ti", 1.0, 30, 60], ["W", 1.0, 20, 40]], "xp": 700},
	"irradiated_hulk": {"name": "Irradiated Hulk", "hp": 290000, "atk": 2700, "def": 185, "interval": 4.0, "loot": [["credits", 1.0, 3000000, 5000000], ["U", 1.0, 400, 500], ["RadIsotope", 1.0, 5, 10]], "xp": 1200},
	"plasma_wraith": {"name": "Plasma Wraith", "hp": 240000, "atk": 2900, "def": 175, "interval": 1.8, "loot": [["credits", 1.0, 1500000, 2000000]], "xp": 1500},
	"shard_swarm": {"name": "Shard Swarm", "hp": 600000, "atk": 5000, "def": 260, "interval": 0.8, "loot": [["credits", 1.0, 20000, 40000], ["VoidCrystal", 1.0, 3, 6], ["Si", 1.0, 50, 100]], "xp": 2000},
	"prism_guardian": {"name": "Prism Guardian", "hp": 650000, "atk": 5400, "def": 300, "interval": 2.5, "loot": [["credits", 1.0, 30000, 60000], ["VoidCrystal", 1.0, 5, 10], ["ExoticMatter", 1.0, 2, 4]], "xp": 2500},
	"rogue_architect": {"name": "Rogue Architect", "hp": 6000, "atk": 180, "def": 45, "interval": 2.0, "loot": [["credits", 1.0, 10000, 20000], ["W", 1.0, 5, 10], ["Cu", 1.0, 20, 50]], "xp": 1000},
	"silicate_monolith": {"name": "Silicate Monolith", "hp": 12000, "atk": 350, "def": 65, "interval": 4.0, "loot": [["credits", 1.0, 3000, 5000], ["Si", 1.0, 50, 100]], "xp": 1500},
	"martian_warmaster": {"name": "Martian Warmaster", "hp": 45000, "atk": 1500, "def": 110, "interval": 2.5, "loot": [["credits", 1.0, 10000, 20000], ["Steel", 1.0, 20, 40]], "xp": 5000},
	"cryo_lord": {"name": "Cryo-Lord", "hp": 65000, "atk": 1200, "def": 150, "interval": 3.0, "loot": [["credits", 1.0, 25000, 45000], ["Ti", 1.0, 50, 100]], "xp": 8000},
	"xenon_harbinger": {"name": "Xenon Harbinger", "hp": 80000, "atk": 1000, "def": 70, "interval": 2.0, "loot": [["credits", 1.0, 80000, 150000], ["VoidArtifact", 1.0, 5, 10]], "xp": 6000},
	"overseer_prime": {"name": "Overseer Prime", "hp": 350000, "atk": 3000, "def": 250, "interval": 3.0, "loot": [["credits", 1.0, 200000, 400000], ["AdvCircuit", 1.0, 50, 100]], "xp": 50000},
	"rad_beast_alpha": {"name": "Rad-Beast Alpha", "hp": 650000, "atk": 5000, "def": 350, "interval": 2.5, "loot": [["credits", 1.0, 500000, 1000000], ["RadIsotope", 1.0, 20, 40]], "xp": 100000},
	"prismatic_sovereign": {"name": "Prismatic Sovereign", "hp": 2500000, "atk": 9000, "def": 500, "interval": 2.0, "loot": [["credits", 1.0, 1000000, 2000000], ["ExoticMatter", 1.0, 10, 20]], "xp": 250000},
	"patient_zero": {"name": "Patient Zero", "hp": 5000000, "atk": 15000, "def": 750, "interval": 1.5, "loot": [["credits", 1.0, 3000000, 5000000], ["BiohazardSample", 1.0, 50, 100]], "xp": 1000000},
	"time_weaver": {"name": "The Time Weaver", "hp": 30000000, "atk": 50000, "def": 2500, "interval": 1.0, "loot": [["credits", 1.0, 20000000, 50000000], ["VoidEssence", 1.0, 20, 50]], "xp": 5000000},
}

const ZONES := [
	{"id": "lunar_orbit", "name": "Lunar Orbit", "desc": "Low threat sector populated by rogue mining drones.", "difficulty": 1, "enemies": ["lunar_drone", "dust_mite", "scrap_collector", "survey_probe", "rogue_architect"]},
	{"id": "asteroid_belt", "name": "Asteroid Belt", "desc": "Dense field with pirate skiffs and kinetic hazards.", "difficulty": 2, "enemies": ["pirate_skiff", "rock_golem", "claim_jumper", "ore_hauler", "silicate_monolith"]},
	{"id": "mars_debris", "name": "Mars Debris Field", "desc": "Wreckage of the old Martian shipyards. Scavengers abound.", "difficulty": 3, "enemies": ["scavenger_mech", "martian_sentry", "derelict_frigate", "salvage_swarm", "martian_warmaster"]},
	{"id": "titan_halo", "name": "Titan's Halo", "desc": "Frozen rings around the gas giant. Extreme cold and pirate lords.", "difficulty": 4, "enemies": ["cryo_drone", "pirate_gunship", "frozen_hulk", "smuggler_cutter", "titan_overseer", "cryo_lord"]},
	{"id": "sector_alpha", "name": "Sector Alpha", "desc": "Uncharted region rich in Titanium. High threat.", "difficulty": 5, "enemies": ["alien_frigate", "xenon_corvette", "xenon_mothership", "xenon_scout", "alien_probe", "xenon_harbinger"]},
	{"id": "sector_beta", "name": "Sector Beta", "desc": "Abandoned mining colony. Automated defense systems hostile. Rich in industrial metals.", "difficulty": 6, "enemies": ["mining_sentinel", "defense_turret", "colony_overseer", "repair_drone", "ore_guardian", "overseer_prime"]},
	{"id": "sector_gamma", "name": "Sector Gamma", "desc": "Radioactive nebula. Mutated organisms detected. Extreme danger.", "difficulty": 7, "enemies": ["radiation_beast", "nebula_leviathan", "gamma_colossus", "irradiated_hulk", "plasma_wraith", "rad_beast_alpha"]},
	{"id": "sector_delta", "name": "Sector Delta", "desc": "Crystalline asteroid field. Unknown energy signatures. Ultimate challenge.", "difficulty": 8, "enemies": ["crystal_golem", "energy_wraith", "sentinel_prime", "shard_swarm", "prism_guardian", "prismatic_sovereign"]},
	{"id": "sector_zeta", "name": "Sector Zeta", "desc": "Sealed sector containing ancient alien pathogens and rogue AI. Extreme biohazard.", "difficulty": 9, "enemies": ["plague_drone", "bio_horror", "rogue_ai_core", "quarantine_warden", "patient_zero"]},
	{"id": "sector_epsilon", "name": "Sector Epsilon", "desc": "Beyond known space. Primordial entities and temporal anomalies. Requires Dreadnought-class vessel.", "difficulty": 10, "enemies": ["void_stalker", "temporal_phantom", "omega_sentinel", "primordial_titan", "void_leviathan", "time_weaver"]},
]

func res_name(sym: String) -> String:
	return RESOURCES.get(sym, {}).get("name", sym)

func color_for(sym: String) -> Color:
	return Color.html(RESOURCES.get(sym, {}).get("color", "ffffff"))

func value_of(sym: String) -> int:
	return int(RESOURCES.get(sym, {}).get("value", 0))

func fmt(n) -> String:
	var v := int(n)
	if v >= 1000000: return "%.2fM" % (v / 1000000.0)
	if v >= 1000: return "%.1fK" % (v / 1000.0)
	return str(v)
