import json, os, re

# ---------------------------------------------------------------------------
# gen_data.py — regenerate scripts/core/game_data.gd from the NEW MissionFlow
# (horizonidle v109) data export under tools/missionflow_data/*.json.
#
# Emits the SAME sections/field-names the mobile runtime consumes (see
# gen_data_OLD.py) but with the new IDs/fields. Combat-relevant deltas:
#   * ENEMIES carry resist_k/resist_e/resist_x/dmg_type/eva/zone/is_boss
#     (+ resist_cryo / warp_hardened so late-zone data stays faithful).
#   * MODULES map slot_type -> "slot"; unique/set modules feed SET_MODULES/SETS.
#   * ZONES (11) + HULLS (10) regenerated; CONST block exposes the DEF_K_* /
#     MAX_DAMAGE_REDUCTION constants to game_state.gd.
# ---------------------------------------------------------------------------

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "missionflow_data")
OUT = os.path.abspath(os.path.join(HERE, "..", "scripts", "core", "game_data.gd"))

def load(name):
    return json.load(open(os.path.join(DATA, name)))

elements = load("elements.json")
gather = load("gather.json")
recipes = load("recipes.json")
tech = load("tech_tree.json")
repeatable = load("repeatable_tech.json")
zones = load("zones.json")
enemies = load("enemies.json")
buildings = load("buildings.json")
hulls = load("hulls.json")
modules = load("modules.json")
gems = load("gems.json")
trinity_sets = load("trinity_sets.json")
consumables = load("consumables.json")
missions = load("missions.json")
combat_consts = load("combat_consts.json")

# ---- colors by element category ----
CAT_COLOR = {
    "Raw Material": "b0895a", "Commodity": "b0895a", "Noble Gas": "7fd0e0",
    "Alkali Metal": "e0734f", "Alkaline Earth Metal": "e0a24f",
    "Transition Metal": "c4c8d0", "Post-Transition Metal": "9aa3af",
    "Post-transition Metal": "9aa3af", "Metal": "c4c8d0",
    "Metalloid": "9ad36a", "Reactive Nonmetal": "6ad36a", "Nonmetal": "6ad36a",
    "Halogen": "d06ad0", "Lanthanide": "8a7ad6", "Actinide": "b07ad6",
    "Component": "5ad1e0", "Alloy": "cfd3da", "Refined Material": "5ad17a",
    "Crafted": "5ad17a", "Crafted Material": "5ad17a", "Fuel": "e0654f",
    "Ammo": "e0654f", "Ammunition": "e0654f", "Consumable": "e0b44f",
    "Artifact": "b07ad6", "Exotic": "e05fb0", "Data": "9aa3af",
    "Combat Data": "9aa3af", "Blueprint": "8a7ad6", "Boss Core": "b07ad6",
    "Module": "5ad1e0", "Trophy": "9aa3af",
}
def color_for(cat, tier):
    return CAT_COLOR.get(cat, "9aa3af")

def elem_value(e):
    v = e.get("base_value")
    if v is None:
        v = e.get("value", 0)
    try:
        return int(v or 0)
    except (TypeError, ValueError):
        return 0

# ---- base resource table from elements.json ----
RES = {}
for e in elements:
    sym = e["symbol"]
    RES[sym] = {
        "name": e.get("name", sym),
        "color": color_for(e.get("category", ""), e.get("tier", 0)),
        "value": elem_value(e),
    }

def prettify(sym):
    return re.sub(r'(?<!^)(?=[A-Z])', ' ', sym).strip()

def ensure(sym):
    if sym not in RES:
        RES[sym] = {"name": prettify(sym), "color": "9aa3af", "value": 1}

# collect symbols referenced everywhere so display never shows a raw id
for a in gather.values():
    for row in a.get("loot_table", []):
        ensure(row[0])
for r in recipes.values():
    for s in r.get("input", {}): ensure(s)
    for s in r.get("output", {}): ensure(s)
    for row in r.get("output_table", []): ensure(row[0])
for en in enemies.values():
    for row in en.get("loot", []): ensure(row[0])
    for row in en.get("rare_loot", []): ensure(row[0])
for t in tech.values():
    for s in t.get("cost_items", {}): ensure(s)
for b in buildings.values():
    for s in b.get("cost", {}):
        if s != "credits": ensure(s)
    for s in b.get("input", {}): ensure(s)
    for s in b.get("yield", {}): ensure(s)
    for s in b.get("yield_bonus", {}): ensure(s)
for h in hulls.values():
    for s in h.get("cost", {}):
        if s != "credits": ensure(s)
for mo in modules.values():
    for s in mo.get("cost", {}):
        if s != "credits": ensure(s)
for gid in gems:
    ensure(gid)
for cid in consumables:
    ensure(cid)

# ---- emit helpers ----
def g(v):
    """GDScript literal for a python value."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, list):
        return "[" + ", ".join(g(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{g(k)}: {g(val)}" for k, val in v.items()) + "}"
    if v is None:
        return '""'
    return g(str(v))

lines = []
lines.append("extends Node")
lines.append("## AUTO-GENERATED by tools/gen_data.py from tools/missionflow_data (horizonidle v109).")
lines.append("## Autoloaded as `GameData`.")
lines.append("")

# COMBAT CONSTANTS (exposed for game_state.gd resolve_damage)
lines.append("const DEF_K_CONSTANT := %s" % g(float(combat_consts.get("DEF_K_CONSTANT", 40.0))))
lines.append("const DEF_K_ZONE_SCALE := %s" % g(float(combat_consts.get("DEF_K_ZONE_SCALE", 30.0))))
lines.append("const DEF_K_ZONE_EXP := %s" % g(float(combat_consts.get("DEF_K_ZONE_EXP", 1.3))))
lines.append("const MAX_DAMAGE_REDUCTION := %s" % g(float(combat_consts.get("MAX_DAMAGE_REDUCTION", 0.8))))
lines.append("")

# RESOURCES
lines.append("const RESOURCES := {")
for sym, d in RES.items():
    lines.append(f'\t{g(sym)}: {{"name": {g(d["name"])}, "color": {g(d["color"])}, "value": {d["value"]}}},')
lines.append("}")
lines.append("")

# GATHER
lines.append('const GATHER_CATS := [')
lines.append('\t{"id": "terrestrial", "label": "Terrestrial"},')
lines.append('\t{"id": "orbital", "label": "Orbital"},')
lines.append('\t{"id": "void", "label": "Void"},')
lines.append(']')
lines.append("const GATHER := {")
for gid, a in gather.items():
    d = {
        "name": a["name"],
        "loot": a.get("loot_table", []),
        "xp": a.get("xp", 0),
        "level_req": a.get("level_req", 1),
        "duration": a.get("duration", 4.0),
        "category": a.get("category", "terrestrial"),
    }
    if a.get("research_req"):
        d["research_req"] = a["research_req"]
    lines.append(f"\t{g(gid)}: {g(d)},")
lines.append("}")
lines.append("")

# CRAFT (processing recipes) — category honoured if present, else keyword rules
RACK_LABELS = {
    "basics": "Basic Operations", "smelting": "Refining", "alloys": "Alloy Fabrication",
    "materials": "Advanced Materials", "components": "Components", "electronics": "Electronics",
    "batteries": "Power Cells", "munitions": "Munitions", "consumables_hull": "Hull Repair",
    "consumables_shield": "Shield Kits", "research": "Research & Artifacts", "salvage": "Salvage",
    "endgame": "Endgame", "processing": "Processing", "trophies": "Trophies",
}
RACK_ORDER = ["basics", "smelting", "alloys", "materials", "components", "electronics",
              "batteries", "munitions", "consumables_hull", "consumables_shield", "research",
              "salvage", "endgame", "processing", "trophies"]
def _has(rid, *kw):
    return any(k in rid for k in kw)
def recipe_category(rid, data):
    if data.get("category"):
        return data["category"]
    if _has(rid, "slug", "cell_t", "craft_cell", "rounds"): return "munitions"
    if "battery" in rid: return "batteries"
    if _has(rid, "circuit", "chip", "semiconductor", "hydraulics"): return "electronics"
    if _has(rid, "artifact", "res1", "res2", "res3", "nav_data", "decrypt"): return "research"
    if _has(rid, "bronze", "steel", "alloy", "galvanize", "stainless"): return "alloys"
    if _has(rid, "smelt", "refine", "extract", "centrifuge", "electrolysis", "leach", "process_", "panning"): return "smelting"
    if _has(rid, "sift", "charcoal", "burn", "wash"): return "basics"
    if _has(rid, "fiber", "polymer", "graphite", "nanoweave", "mesh", "sealant", "coolant", "carbon"): return "materials"
    return "materials"

_recipe_cat = {rid: recipe_category(rid, r) for rid, r in recipes.items()}
_used_cats = [c for c in RACK_ORDER if c in _recipe_cat.values()]
for c in _recipe_cat.values():
    if c not in _used_cats:
        _used_cats.append(c)
lines.append("const CRAFT_CATS := [")
for cid in _used_cats:
    lines.append(f'\t{{"id": {g(cid)}, "label": {g(RACK_LABELS.get(cid, cid.replace("_", " ").title()))}}},')
lines.append("]")
lines.append("const CRAFT := {")
for rid, r in recipes.items():
    inputs = dict(r.get("input", {}))
    outputs = dict(r.get("output", {}))
    if r.get("credits_cost"):
        inputs["credits"] = int(r["credits_cost"])
    if r.get("credits_output"):
        outputs["credits"] = int(r["credits_output"])
    d = {
        "name": r["name"],
        "inputs": inputs,
        "outputs": outputs,
        "bonus": r.get("output_table", []),
        "xp": r.get("xp", 0),
        "level_req": r.get("level_req", 1),
        "duration": r.get("duration", 4.0),
        "category": _recipe_cat[rid],
    }
    if r.get("research_req"):
        d["research_req"] = r["research_req"]
    lines.append(f"\t{g(rid)}: {g(d)},")
lines.append("}")
lines.append("")

# RESEARCH (tech tree). desc = description/flavor; parent chain preserved.
# req_tech (a real prerequisite distinct from parent) is normalized to a list so
# game_state can require ALL of them unlocked. requires_warp gates prestige tech.
def req_tech_list(t):
    rt = t.get("req_tech")
    if not rt:
        return []
    return rt if isinstance(rt, list) else [rt]

lines.append("const RESEARCH := {")
for tid, t in tech.items():
    d = {
        "name": t.get("name", tid),
        "desc": (t.get("flavor") or t.get("description", "") or "").replace("\n", " · "),
        "credits": int(t.get("cost", 0)),
        "items": t.get("cost_items", {}),
        "parent": t.get("parent") or "",
        "req_tech": req_tech_list(t),
        "requires_warp": bool(t.get("requires_warp", False)),
        "category": t.get("category", ""),
    }
    lines.append(f"\t{g(tid)}: {g(d)},")
lines.append("}")
lines.append("")

# ENEMIES — carry full combat data (resists, dmg_type, eva, zone, is_boss).
lines.append("const ENEMIES := {")
for eid, en in enemies.items():
    st = en.get("stats", {})
    loot = []
    for row in en.get("loot", []):
        if len(row) == 3:
            loot.append([row[0], 1.0, row[1], row[2]])
        elif len(row) == 4:
            loot.append(row)
    # rare_loot is [id, chance, min, max] — fold into the weighted loot table.
    for row in en.get("rare_loot", []):
        if len(row) == 4:
            loot.append([row[0], float(row[1]), int(row[2]), int(row[3])])
    d = {
        "name": en.get("name", eid),
        "hp": st.get("hp", 10),
        "atk": st.get("atk", 1),
        "def": st.get("def", 0),
        "interval": st.get("atk_interval", 2.0),
        "accuracy": st.get("accuracy", 0),
        "max_shield": st.get("max_shield", 0),
        "eva": en.get("eva", 0),
        "zone": en.get("zone", 1),
        "dmg_type": en.get("dmg_type", "kinetic"),
        "resist_k": en.get("resist_k", 0.0),
        "resist_e": en.get("resist_e", 0.0),
        "resist_x": en.get("resist_x", 0.0),
        "resist_cryo": en.get("resist_cryo", 0.0),
        "warp_hardened": en.get("warp_hardened", False),
        # v109 P3 boss mechanic: per-enemy Enrage (HP fraction + ATK surge).
        "enrage_at": float(en.get("enrage_at", 0.0)),
        "enrage_atk_mult": float(en.get("enrage_atk_mult", 1.5)),
        "is_boss": en.get("is_boss", False),
        # v80.1 boss-core drop: zone bosses grant their ZN_Core on kill (gates
        # zone_N_access research). Empty string for non-boss / coreless enemies.
        "boss_core": en.get("boss_core") or "",
        "drop_chance": en.get("module_drop_chance", 0.0),
        "drop_pool": en.get("module_drop_pool", []),
        "loot": loot,
        "xp": en.get("xp", 0),
    }
    lines.append(f"\t{g(eid)}: {g(d)},")
lines.append("}")
lines.append("")

# ZONES (ordered by difficulty for a stable display/progression order).
lines.append("const ZONES := [")
for zid, z in sorted(zones.items(), key=lambda kv: kv[1].get("difficulty", 1)):
    d = {
        "id": zid,
        "name": z.get("name", zid),
        "desc": z.get("desc", ""),
        "difficulty": z.get("difficulty", 1),
        "enemies": [e for e in z.get("enemies", []) if e in enemies],
    }
    if z.get("research_req"):
        d["research_req"] = z["research_req"]
    lines.append(f"\t{g(d)},")
lines.append("]")
lines.append("")

# HAZARD_ZONES — gauntlet "dungeons" (v86.0). Unlocked once unlock_boss has a
# kill; runs max_waves waves (regular pool, elite at max_waves-2, boss at
# max_waves-1), scaling enemy hp/atk/shield x(1+wave*0.20). Data-driven so any
# future hazard works without code changes.
hazard_zones = load("hazard_zones.json")
lines.append("const HAZARD_ZONES := {")
for hz_id, hz in hazard_zones.items():
    d = {
        "name": hz.get("name", hz_id),
        "desc": hz.get("desc", ""),
        "unlock_boss": hz.get("unlock_boss", ""),
        "counter_module": hz.get("counter_module", ""),
        "hazard_type": hz.get("hazard_type", ""),
        "max_waves": int(hz.get("max_waves", 7)),
        "enemy_pool": [e for e in hz.get("enemy_pool", []) if e in enemies],
        "elite_enemy": hz.get("elite_enemy", ""),
        "boss_enemy": hz.get("boss_enemy", ""),
        "first_clear_reward": hz.get("first_clear_reward", ""),
        "difficulty": int(hz.get("zone_difficulty", 3)),
    }
    lines.append(f"\t{g(hz_id)}: {g(d)},")
lines.append("}")
lines.append("")

# RESEARCH_GRAPHS — auto-laid-out per-category tab. The mobile research view
# draws nodes at pos[id] and parent branches via RESEARCH[id].parent, so a
# tier-column / stacked-row layout reproduces the desktop tree shape.
CAT_TAB = {
    "gathering": "Operations", "infrastructure": "Operations", "meta": "Operations",
    "processing": "Engineering",
    "ships": "Ships", "combat": "Ships", "zone": "Ships",
}
TAB_ORDER = ["Operations", "Engineering", "Ships"]
COL_W = 220.0
ROW_H = 110.0
tab_nodes = {tab: [] for tab in TAB_ORDER}
for tid, t in tech.items():
    tab = CAT_TAB.get(t.get("category", ""), "Engineering")
    tab_nodes[tab].append(tid)
lines.append("const RESEARCH_TABS := %s" % g(TAB_ORDER))
lines.append("const RESEARCH_GRAPHS := {")
for tab in TAB_ORDER:
    ids = tab_nodes[tab]
    # column = tier, row = running index within that tier
    row_count = {}
    pos_items = []
    for tid in sorted(ids, key=lambda x: (tech[x].get("tier", 0), x)):
        tier = int(tech[tid].get("tier", 0))
        row = row_count.get(tier, 0)
        row_count[tier] = row + 1
        pos_items.append((tid, tier * COL_W + 40.0, row * ROW_H + 40.0))
    pos_str = "{" + ", ".join('%s: Vector2(%g, %g)' % (g(t), x, y) for t, x, y in pos_items) + "}"
    node_ids = [t for t, _, _ in pos_items]
    lines.append(f"\t{g(tab)}: {{\"nodes\": {g(node_ids)}, \"pos\": {pos_str}}},")
lines.append("}")
lines.append("")

# BUILDINGS (infrastructure)
lines.append("const BUILDING_CATS := [")
for cid, lbl in [("power", "Power"), ("extraction", "Extraction"), ("industry", "Industry"), ("logistics", "Logistics")]:
    lines.append(f'\t{{"id": {g(cid)}, "label": {g(lbl)}}},')
lines.append("]")
lines.append("const BUILDINGS := {")
for bid, b in buildings.items():
    d = {
        "name": b.get("name", bid),
        "desc": b.get("description", ""),
        "cost": b.get("cost", {}),
        "yield": b.get("yield", {}),
        "input": b.get("input", {}),
        "energy_gen": b.get("energy_gen", 0.0),
        "energy_cons": b.get("energy_cons", 0.0),
        "interval": b.get("interval", 1.0),
        "category": b.get("category", "industry"),
    }
    if b.get("research_req"): d["research_req"] = b["research_req"]
    if b.get("max"): d["max"] = b["max"]
    if b.get("yield_bonus"): d["yield_bonus"] = b["yield_bonus"]
    if b.get("special"): d["special"] = b["special"]
    lines.append(f"\t{g(bid)}: {g(d)},")
lines.append("}")
lines.append("")

# SHIPYARD: hulls + modules
lines.append("const HULLS := {")
for hid, h in hulls.items():
    st = h.get("stats", {})
    d = {
        "name": h.get("name", hid),
        "hp": st.get("hp", 100),
        "atk": st.get("atk", 0),
        "energy_capacity": st.get("energy_capacity", 0),
        "cost": h.get("cost", {}),
        "slots": h.get("slots", []),
        "tier": h.get("tier", 0),
    }
    if h.get("research_req"): d["research_req"] = h["research_req"]
    lines.append(f"\t{g(hid)}: {g(d)},")
lines.append("}")
lines.append('const SLOT_LABELS := {"weapon": "Weapon", "shield": "Shield", "engine": "Engine", "battery": "Battery", "sensor": "Sensor", "cooling": "Cooling", "armor": "Armor", "gem": "Core", "gem_synth": "Core"}')

# v110 battery-only energy model (desktop ref_shipyard_manager.gd ~L56-79):
# every consumer module DRAWS CONSUMER_LOAD_BY_TIER[tier]; every battery SUPPLIES
# BATTERY_CAP_BY_TIER[tier]. Desktop DERIVES these by tier (not stored per-module)
# from the module's power_tier override, else its zone. We BAKE the derived value
# into the emitted stats so game_state's existing st.get("energy_load") /
# st.get("energy_capacity") reads draw/supply power faithfully. Index = tier-1.
CONSUMER_LOAD_BY_TIER = [10, 15, 25, 40, 60, 100, 150, 220, 350, 500]
BATTERY_CAP_BY_TIER   = [30, 60, 75, 150, 180, 350, 600, 750, 1330, 1700]
CONSUMER_SLOT_TYPES = ["weapon", "shield", "armor", "engine", "sensor"]

def module_tier(mo):
    if mo.get("power_tier"):
        t = int(mo["power_tier"])
    else:
        t = int(mo.get("zone", mo.get("zone_difficulty", 1)))
    return max(1, min(t, len(CONSUMER_LOAD_BY_TIER)))

def derive_energy_stats(mo, stats):
    """Bake desktop tier->load / tier->capacity into a copy of the stats dict."""
    slot = mo.get("slot_type", "")
    st = dict(stats)
    if slot in CONSUMER_SLOT_TYPES:
        st["energy_load"] = CONSUMER_LOAD_BY_TIER[module_tier(mo) - 1]
    elif slot == "battery":
        st["energy_capacity"] = BATTERY_CAP_BY_TIER[module_tier(mo) - 1]
    return st

# Split set/unique modules out into SET_MODULES; everything else into MODULES.
set_module_ids = {mid for mid, m in modules.items() if m.get("set_id")}
lines.append("const MODULES := {")
for mid, mo in modules.items():
    if mid in set_module_ids:
        continue
    d = {
        "name": mo.get("name", mid),
        "slot": mo.get("slot_type", ""),
        "stats": derive_energy_stats(mo, mo.get("stats", {})),
        "cost": mo.get("cost", {}),
        "desc": (mo.get("desc", "") or "").replace("\n", " "),
        "zone": int(mo.get("zone", mo.get("zone_difficulty", 1))),
    }
    if mo.get("power_tier"): d["power_tier"] = int(mo["power_tier"])
    if mo.get("rarity") is not None: d["rarity"] = mo["rarity"]
    if mo.get("research_req"): d["research_req"] = mo["research_req"]
    lines.append(f"\t{g(mid)}: {g(d)},")
lines.append("}")
lines.append("")

# SET_MODULES + SETS (3-piece trinity sets). Each set piece is z{n}_unique_{slot};
# set_id maps to trinity_sets.json (name + bonus). boss = the zone boss that drops it.
SET_BOSS = {}
for zid, z in zones.items():
    diff = z.get("difficulty", 0)
    for e in z.get("enemies", []):
        if enemies.get(e, {}).get("is_boss"):
            SET_BOSS[f"z{diff}"] = e
            break
# Map known trinity bonuses onto the mobile combat hooks game_state already
# implements (cryo / sovereign / patient_zero). Unmapped sets carry their data
# but apply no special runtime hook (stat bonuses still stack from the pieces).
SET_BONUS_HOOK = {
    "wardens_quarantine": ("patient_zero", "Regenerate hull during combat"),
    "sovereigns_prism": ("sovereign", "Chance to reflect incoming damage"),
}

lines.append("const SET_MODULES := {")
for mid, m in modules.items():
    if mid not in set_module_ids:
        continue
    sid = m.get("set_id", "")
    d = {
        "name": m.get("name", mid),
        "slot": m.get("slot_type", ""),
        "stats": derive_energy_stats(m, m.get("stats", {})),
        "desc": (m.get("desc", "") or "").replace("\n", " "),
        "rarity": m.get("rarity", 4),
        "zone": int(m.get("zone", m.get("zone_difficulty", 1))),
        "set": sid,
    }
    if m.get("power_tier"): d["power_tier"] = int(m["power_tier"])
    lines.append(f"\t{g(mid)}: {g(d)},")
lines.append("}")

# group pieces by set_id
set_pieces = {}
for mid, m in modules.items():
    if mid in set_module_ids:
        set_pieces.setdefault(m["set_id"], []).append(mid)
lines.append("const SETS := {")
for sid, sdef in trinity_sets.items():
    pieces = set_pieces.get(sid, [])
    if not pieces:
        continue
    zpref = pieces[0].split("_")[0]  # e.g. "z1"
    hook, hook_desc = SET_BONUS_HOOK.get(sid, ("", ""))
    d = {
        "name": sdef.get("name", sid),
        "pieces": pieces,
        "boss": SET_BOSS.get(zpref, ""),
        "bonus": hook,
        "bonus_desc": hook_desc,
        "trinity": sdef.get("bonus", {}),
    }
    lines.append(f"\t{g(sid)}: {g(d)},")
lines.append("}")

# TRINITY_SET_BONUSES — raw desktop bonus table (set_id -> {pieces, bonus...}).
lines.append("const TRINITY_SET_BONUSES := {")
for sid, sdef in trinity_sets.items():
    d = {"name": sdef.get("name", sid), "pieces": sdef.get("pieces", 3)}
    d.update(sdef.get("bonus", {}))
    lines.append(f"\t{g(sid)}: {g(d)},")
lines.append("}")

# GEMS (GEM_GLOBAL_EFFECTS)
GEM_NAMES = {"Crimson": "Crimson Core", "Cobalt": "Cobalt Core", "Topaz": "Topaz Core", "Amethyst": "Amethyst Core"}
lines.append("const GEMS := {")
for gid, eff in gems.items():
    tier = "Cracked" if gid.startswith("Cracked") else ("Stable" if gid.startswith("Stable") else "Pristine")
    color = gid.replace("Cracked", "").replace("Stable", "").replace("Pristine", "").replace("Core", "")
    lines.append(f'\t{g(gid)}: {{"name": {g(tier + " " + GEM_NAMES.get(color, color))}, "effects": {g(eff)}}},')
lines.append("}")
lines.append("")

# CONSUMABLES (auto-use repair / shield kits)
lines.append('const CONSUMABLES := {')
for cid, c in consumables.items():
    d = {"type": c.get("type", "hull"), "heal_pct": c.get("heal_pct", 0.0), "name": c.get("name", cid)}
    lines.append(f"\t{g(cid)}: {g(d)},")
lines.append('}')
lines.append("")

# MISSIONS — port the new mission chain into the mobile schema
# ({name, desc, type, target, qty, cr, xp, next}). MISSION_ORDER follows the
# m-chain via next_mission from m001 (the prestige goal_* cores are kept in
# MISSIONS but not in the tutorial walk order).
#
# Mobile description overrides: the desktop tutorial text references the
# desktop UI (drag-and-drop Ship Designer with an "Armory" panel, a left
# sidebar, "Engineering/Processing/Mine/Shipyard" page names, and trophies)
# which don't exist on mobile. Mobile UI: bottom bar = Gather · Craft ·
# Combat · Research · More; modules are BUILT and hulls CONSTRUCTED in the
# Ship Designer (tap to equip; ammo + consumable slots live there too);
# materials/ammo/consumables are crafted on the Craft tab. These overrides
# fix the instructions for mobile WITHOUT changing any mission
# type/target/qty/reward/chain (the gameplay loop is identical).
MOBILE_MISSION_DESC = {
    "m005": "On the Craft tab, process Dirt to extract 100 Silicon and 80 Iron.",
    "m007": "In the Shipyard, build a Basic Thruster (Ion Thrusters).",
    "m007b": "In the Ship Designer, tap your Basic Thruster to equip it into an ENGINE slot. Evasion rises the moment it's seated.",
    "m011": "On the Craft tab, produce 50 Carbon (Charcoal Kiln recipe).",
    "m012": "On the Gather tab, extract 100 Spodumene (the lithium-bearing ore).",
    "m013": "On the Craft tab, refine 50 Lithium.",
    "m013b": "On the Gather tab, extract 100 Malachite (copper ore).",
    "m013c": "On the Craft tab, refine 50 Copper.",
    "m015": "In the Shipyard, build a Mass Driver Mk.I.",
    "m015b": "In the Ship Designer, tap your Mass Driver to equip it into a WEAPON slot. Your ship can finally deal damage.",
    "m016": "On the Craft tab, produce 100 Ferrite Rounds (SlugT1), then load them into your weapon's ammo slot in the Ship Designer.",
    "m016b": "In the Ship Designer, equip a WEAPON and a SHIELD.",
    "m016c": "Open the Combat tab, pick a sector, choose a target, and ENGAGE. Your shield soaks hits first; your hull takes the overflow. Once you research Auto-Repair, kits fire automatically at the threshold.",
    "m019": "On the Craft tab, craft 10 Basic Circuitry.",
    "m021": "On the Craft tab, craft 5 Basic Batteries (BatteryT1).",
    "m022": "In the Shipyard, build a Basic Battery module.",
    "m022b": "In the Ship Designer, tap your Basic Battery to equip it into a BATTERY slot. Energy capacity rises — needed to power your weapons and shields.",
    "m024": "In the Shipyard, build a Basic Shield.",
    "m024b": "Repair kits keep you alive in combat. On the Craft tab, craft 5 Emergency Hull Patches and 5 Basic Shield Boosters.",
    "m024b2": "In the Ship Designer, fit a Hull and a Shield repair kit into your consumable slots. In combat, tap the Repair / Shield buttons to spend one and patch up.",
    "m024c": "In the Ship Designer, tap your Basic Shield to equip it into a SHIELD slot. Incoming damage hits the shield before your hull.",
    "m025b": "On the Craft tab, smelt 50 Steel (Basic Steel Smelting recipe).",
    "m026b": "In the Shipyard, construct an Industrial Frigate hull.",
    "m026c": "Defeated enemies drop gear of varying rarity. Farm Lunar Orbit on the Combat tab until you get a RARE (blue) module drop.",
    "m026d": "In the Ship Designer, equip at least one RARE+ weapon.",
    "m028": "On the Gather tab, mine 100 Cassiterite (tin ore).",
    "m029": "In the Shipyard, build the Carbon Fiber Plate armor module.",
    "m029a3": "On the Craft tab, craft 10 Structural Components — the universal building block of heavy industry.",
    "m029b": "On the Craft tab, craft 5 Advanced Circuits (Semiconductor + Gold + Silver + Tin + Structural Components — your earlier research unlocked each one).",
    "m030c": "In the Shipyard, construct a Destroyer hull.",
    "m030f": "On the Combat tab, defeat 3 Scavenger Mechs in the Mars Debris zone.",
    "m030h": "On the Combat tab, defeat 3 Ice Wraiths in the Cryofield. They drop Cryo Essence.",
    "m032c": "In the Shipyard, construct a Battlecruiser.",
    "m032d": "Void Artifacts drop from Sector Alpha ships — defeat them on the Combat tab until you collect 5.",
    "m033c": "In the Shipyard, construct a Dreadnought.",
}

def _mobile_desc(m):
    mid = m.get("id", "")
    if mid in MOBILE_MISSION_DESC:
        return MOBILE_MISSION_DESC[mid]
    d = m.get("description", "") or ""
    # Catch-all terminology fixes for any line not explicitly overridden
    # (e.g. the research chain's "in the Research tree" → "Research tab").
    d = (d.replace("Research tree", "Research tab")
          .replace("Engineering page", "Craft tab")
          .replace("Engineering tab", "Craft tab")
          .replace("Processing page", "Craft tab")
          .replace("Mine page", "Gather tab")
          .replace("the Shipyard", "the Ship Designer")
          .replace("left sidebar", "More menu"))
    return d

def mission_dict(m):
    tgt = m.get("target", "")
    # gather_multi targets are dicts {sym: qty}
    return {
        "name": m.get("name", m.get("id", "")),
        "desc": _mobile_desc(m),
        "type": m.get("type", "gather"),
        "target": tgt,
        "qty": int(m.get("target_qty", 1)),
        "cr": int(m.get("reward_cr", 0)),
        "xp": int(m.get("reward_xp", 0)),
        "next": m.get("next_mission", "") or "",
    }

lines.append("const MISSIONS := {")
for mid, m in missions.items():
    lines.append(f"\t{g(mid)}: {g(mission_dict(m))},")
lines.append("}")

# Build MISSION_ORDER by walking next_mission from m001.
order = []
present = set(missions.keys())
cur = "m001" if "m001" in present else (sorted(present)[0] if present else "")
seen = set()
while cur and cur in present and cur not in seen:
    seen.add(cur)
    order.append(cur)
    cur = missions[cur].get("next_mission", "") or ""
# append any leftover m-missions not reached by the walk (keeps data complete)
for mid in missions:
    if mid.startswith("m") and mid not in seen:
        order.append(mid)
lines.append('const MISSION_ORDER := %s' % g(order))
# MISSION_GOALS — standalone "core goal" missions that are always active (no
# `next` chain pointer). Desktop's mission_manager activates these on init
# alongside the tutorial head; mobile surfaces them the same way.
goals = [mid for mid, m in missions.items() if m.get("active", False) and mid not in seen]
lines.append('const MISSION_GOALS := %s' % g(goals))
lines.append("")

# REPEATABLE — infinite-scaling recursion research (from repeatable_tech.json).
# Mobile schema: {name, desc, base_cost, items, bonus_type, bonus_value}.
def repeatable_dict(r):
    return {
        "name": r.get("name", ""),
        "desc": r.get("description", ""),
        "base_cost": int(r.get("base_cost", 100000)),
        "items": dict(r.get("base_items", {})),
        "bonus_type": r.get("bonus_type", ""),
        "bonus_value": float(r.get("bonus_value", 0.05)),
    }
lines.append("const REPEATABLE := {")
for rid, r in repeatable.items():
    lines.append(f"\t{g(rid)}: {g(repeatable_dict(r))},")
lines.append("}")
lines.append('const REPEATABLE_ORDER := %s' % g(sorted(repeatable.keys())))
lines.append("")

# helpers (unchanged API the runtime depends on)
lines.append("func res_name(sym: String) -> String:")
lines.append('\treturn RESOURCES.get(sym, {}).get("name", sym)')
lines.append("")
lines.append("func color_for(sym: String) -> Color:")
lines.append('\treturn Color.html(RESOURCES.get(sym, {}).get("color", "ffffff"))')
lines.append("")
lines.append("func value_of(sym: String) -> int:")
lines.append('\treturn int(RESOURCES.get(sym, {}).get("value", 0))')
lines.append("")
lines.append("func fmt(n) -> String:")
lines.append("\tvar v := int(n)")
lines.append('\tif v >= 1000000: return "%.2fM" % (v / 1000000.0)')
lines.append('\tif v >= 1000: return "%.1fK" % (v / 1000.0)')
lines.append("\treturn str(v)")
lines.append("")

open(OUT, "w").write("\n".join(lines))
print(f"Wrote {OUT}")
print(f"  resources={len(RES)} gather={len(gather)} craft={len(recipes)} research={len(tech)} "
      f"enemies={len(enemies)} zones={len(zones)} hazards={len(hazard_zones)} hulls={len(hulls)} modules={len(modules)} "
      f"sets={len(trinity_sets)} gems={len(gems)} consumables={len(consumables)} missions={len(missions)}")
