import csv
from pathlib import Path

translations = {
    "ACCEPT": "KABUL ET",
    "ACKNOWLEDGE": "ONAYLA",
    "ACTIVE CONTRACTS": "AKTİF SÖZLEŞMELER",
    "ALL": "TÜMÜ",
    "AMMO BAY": "CEPHANELİK",
    "ARMOR": "ZIRH",
    "ARMORY": "CEPHANELİK",
    "ATLAS": "ATLAS",
    "Action Name": "Eylem Adı",
    "All": "Tümü",
    "Alloys": "Alaşımlar",
    "Atlas": "Atlas",
    "BATTERY": "BATARYA",
    "BOUNTY BOARD": "ÖDÜL PANOSU",
    "Base Infrastructure": "Temel Altyapı",
    "Bounties": "Ödül Avları",
    "Build": "İnşa Et",
    "Building Name": "Bina Adı",
    "Buildings": "Binalar",
    "CLAIM ALL (0)": "TÜMÜNÜ AL (0)",
    "CLOSE": "KAPAT",
    "CORVETTE": "KORVET",
    "Claim": "Al",
    "Combat": "Savaş",
    "Components": "Bileşenler",
    "Construct": "İnşa Et",
    "Contract Title": "Sözleşme Başlığı",
    "Contract description": "Sözleşme açıklaması",
    "Costs": "Maliyetler",
    "Craft": "Üret",
    "Description goes here...": "Açıklama buraya gelecek...",
    "Description here...": "Açıklama burada...",
    "Description of the mission goes here.": "Görev açıklaması buraya gelecek.",
    "Description...": "Açıklama...",
    "Drops: ...": "Düşenler: ...",
    "EMPTY": "BOŞ",
    "ENGAGE": "SAVAŞA GİR",
    "ENGINE": "MOTOR",
    "ENTITY TYPE": "VARLIK TÜRÜ",
    "Enemy Name": "Düşman Adı",
    "Engineering": "Mühendislik",
    "Entity Name": "Varlık Adı",
    "Fe": "Fe",
    "Fleet": "Filo",
    "Gathering": "Toplama",
    "HORIZON IDLE": "HORIZON IDLE",
    "Hull Name": "Gövde Adı",
    "IN PROGRESS": "DEVAM EDİYOR",
    "INFO": "BİLGİ",
    "INITIALIZING SECURE LINK...": "GÜVENLİ BAĞLANTI BAŞLATILIYOR...",
    "ITEM DETAILS": "EŞYA DETAYLARI",
    "Idle": "Boşta",
    "Infrastructure": "Altyapı",
    "Inputs": "Girdiler",
    "Intel: Enemy Name": "İstihbarat: Düşman Adı",
    "Inventory": "Envanter",
    "Iron": "Demir",
    "Level: 1": "Seviye: 1",
    "Loot Info": "Ganimet Bilgisi",
    "Lvl 1": "Svy 1",
    "MODULE": "MODÜL",
    "Main Menu": "Ana Menü",
    "Metals": "Metaller",
    "Mine": "Maden",
    "Mission Control": "Görev Kontrol",
    "Mission Name": "Görev Adı",
    "Missions": "Görevler",
    "Module Name": "Modül Adı",
    "No rounds": "Tur yok",
    "OPERATIONS": "OPERASYONLAR",
    "ORDNANCE": "MÜHİMMAT",
    "Offline progress report...": "Çevrimdışı ilerleme raporu...",
    "Open Star Chart": "Yıldız Haritasını Aç",
    "Ores": "Cevherler",
    "Other": "Diğer",
    "Outputs": "Çıktılar",
    "POWER": "GÜÇ",
    "Persistent orders from the Command Network. Quests track passively across all systems — no need to accept. Claim rewards as objectives complete. New orders are issued on each claim.": "Komuta Ağı'ndan gelen kalıcı siparişler. Siparişler tüm sistemlerde pasif olarak takip edilir — kabul etmeye gerek yoktur. Hedefler tamamlandıkça ödülleri alabilirsiniz. Her ödül alımında yeni siparişler verilir.",
    "Pick a material or enemy from the list to view full details.": "Tam detayları görmek için listeden bir malzeme veya düşman seçin.",
    "Planetary Operations": "Gezegensel Operasyonlar",
    "Processing": "İşleme",
    "Qty:": "Mik:",
    "Quest Title": "Sipariş Başlığı",
    "Quest description": "Sipariş açıklaması",
    "Quests": "Siparişler",
    "REFERENCE": "REFERANS",
    "REFRESH (50K CR)": "YENİLE (50B CR)",
    "REPAIR": "TAMİR ET",
    "REROLL BOARD (2.5K CR)": "PANOYU YENİLE (2.5B CR)",
    "RETREAT": "GERİ ÇEKİL",
    "Recipe Name": "Tarif Adı",
    "Refresh in: --": "Yenilenme süresi: --",
    "Research": "Araştırma",
    "Research Lab": "Araştırma Laboratuvarı",
    "Research Network": "Araştırma Ağı",
    "Research Required: ...": "Gereken Araştırma: ...",
    "Reward: 0 CR": "Ödül: 0 CR",
    "Reward: 1,000 CR": "Ödül: 1.000 CR",
    "SELL TO UNION": "BİRLİĞE SAT",
    "SHIELD": "KALKAN",
    "SHIP": "GEMİ",
    "STANDING ORDERS": "MEVCUT SİPARİŞLER",
    "SYSTEM REPORT // OFFLINE LOG": "SİSTEM RAPORU // ÇEVRİMDIŞI GÜNLÜK",
    "Search by name...": "İsme göre ara...",
    "Select an Item": "Bir Eşya Seçin",
    "Sell All Stack": "Tüm Yığını Sat",
    "Sell Items": "Eşyaları Sat",
    "Ship Designer": "Gemi Tasarımcısı",
    "Shipyard": "Tersane",
    "Sources": "Kaynaklar",
    "Start": "Başlat",
    "Stats": "İstatistikler",
    "Stats...": "İstatistikler...",
    "Storage": "Depo",
    "Sys Config": "Sistem Yapılandırması",
    "Target Acquired": "Hedef Tespit Edildi",
    "Tech Name": "Teknoloji Adı",
    "Totally Untranslated String": "Tamamen Çevrilmemiş Metin",
    "USS Horizon": "USS Horizon",
    "UTILITY": "YARDIMCI",
    "Unit Price: -": "Birim Fiyatı: -",
    "Uses": "Kullanım Alanları",
    "WEAPON": "SİLAH",
    "Warp Core": "Warp Çekirdeği",
    "[ EXPEDITION YIELD ]": "[ KEŞİF GETİRİSİ ]",
    "[ EXTRACTION RACKS ]": "[ ÇIKARMA RAFLARI ]",
    "[ LOGISTICS & FABRICATION ]": "[ LOJİSTİK & ÜRETİM ]",
    "[ ORDNANCE FEED ]": "[ MÜHİMMAT BESLEMESİ ]",
    "[ POWER SYSTEMS ]": "[ GÜÇ SİSTEMLERİ ]",
    "[ UNIQUE ]": "[ EŞSİZ ]",
    "[center]Searching for loot paths...[/center]": "[center]Ganimet yolları aranıyor...[/center]"
}

def translate_csv():
    csv_path = Path(r"c:\Users\ilter-cnc\Documents\horizon-idle\horizonidle-godot\localization\strings.csv")
    
    rows = []
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            if not row: continue
            if len(row) > 1 and row[1] == "":
                # Try to translate
                key = row[0]
                if key in translations:
                    row[1] = translations[key]
            rows.append(row)
            
    with open(csv_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(rows)

if __name__ == "__main__":
    translate_csv()
    print("CSV updated with Turkish translations!")
